// flow-typed signature: 04d99e7d505dec42d023844d8d84599e
// flow-typed version: <<STUB>>/@lezer/highlight_v0.16.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lezer/highlight'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lezer/highlight' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lezer/highlight/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lezer/highlight/dist/index' {
  declare module.exports: $Exports<'@lezer/highlight/dist'>;
}
declare module '@lezer/highlight/dist/index.js' {
  declare module.exports: $Exports<'@lezer/highlight/dist'>;
}
