# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# See https://github.com/mozilla-l10n/moz-fluent-linter/blob/main/src/fluent_linter/config.yml
# for details

---
# Check brand names
CO01:
  enabled: true
  brands:
    - Firefox
    - Mozilla
    - Profiler
  exclusions:
    files: []
    messages: []
# Enforce variable comments
VC:
  disabled: false
# Enforce placeholder style, e.g. { $variable }
PS01:
  disabled: false
