// flow-typed signature: b2f76cdf45a9f020ccc81f4258e36209
// flow-typed version: <<STUB>>/@tgwf/co2_v0.11.4/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tgwf/co2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tgwf/co2' {
  declare module.exports: any;
}