// flow-typed signature: a5c51dc9523615165d5ea5360589ad11
// flow-typed version: <<STUB>>/@codemirror/gutter_v^0.19.9/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@codemirror/gutter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@codemirror/gutter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@codemirror/gutter/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@codemirror/gutter/dist/index' {
  declare module.exports: $Exports<'@codemirror/gutter/dist'>;
}
declare module '@codemirror/gutter/dist/index.js' {
  declare module.exports: $Exports<'@codemirror/gutter/dist'>;
}
