// flow-typed signature: a1992581c4e0244712d6eb256b7e11fb
// flow-typed version: <<STUB>>/@codemirror/highlight_v^0.19.7/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@codemirror/highlight'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@codemirror/highlight' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@codemirror/highlight/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@codemirror/highlight/dist/index' {
  declare module.exports: $Exports<'@codemirror/highlight/dist'>;
}
declare module '@codemirror/highlight/dist/index.js' {
  declare module.exports: $Exports<'@codemirror/highlight/dist'>;
}
