// flow-typed signature: 832f9424b0dfb78d04a26bc410cffd45
// flow-typed version: <<STUB>>/@codemirror/lang-cpp_v^0.19.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@codemirror/lang-cpp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@codemirror/lang-cpp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@codemirror/lang-cpp/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@codemirror/lang-cpp/dist/index' {
  declare module.exports: $Exports<'@codemirror/lang-cpp/dist'>;
}
declare module '@codemirror/lang-cpp/dist/index.js' {
  declare module.exports: $Exports<'@codemirror/lang-cpp/dist'>;
}
