// flow-typed signature: 6da7e076f26b0b6130edb61e7b533f97
// flow-typed version: <<STUB>>/@codemirror/lang-javascript_v^0.19.6/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@codemirror/lang-javascript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@codemirror/lang-javascript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@codemirror/lang-javascript/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@codemirror/lang-javascript/dist/index' {
  declare module.exports: $Exports<'@codemirror/lang-javascript/dist'>;
}
declare module '@codemirror/lang-javascript/dist/index.js' {
  declare module.exports: $Exports<'@codemirror/lang-javascript/dist'>;
}
