// flow-typed signature: cd96e92a3de5223e5ca19bd6b5573a83
// flow-typed version: <<STUB>>/@codemirror/language_v0.20.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@codemirror/language'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@codemirror/language' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@codemirror/language/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@codemirror/language/dist/index' {
  declare module.exports: $Exports<'@codemirror/language/dist'>;
}
declare module '@codemirror/language/dist/index.js' {
  declare module.exports: $Exports<'@codemirror/language/dist'>;
}
