// flow-typed signature: 9b6ff8d28258e32821bb7afe547b561e
// flow-typed version: <<STUB>>/@codemirror/rangeset_v0.19.6/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@codemirror/rangeset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@codemirror/rangeset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@codemirror/rangeset/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@codemirror/rangeset/dist/index' {
  declare module.exports: $Exports<'@codemirror/rangeset/dist'>;
}
declare module '@codemirror/rangeset/dist/index.js' {
  declare module.exports: $Exports<'@codemirror/rangeset/dist'>;
}
