// flow-typed signature: da328fc22c17006fa9160f6aac04424f
// flow-typed version: <<STUB>>/@codemirror/state_v^0.19.6/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@codemirror/state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@codemirror/state' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@codemirror/state/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@codemirror/state/dist/index' {
  declare module.exports: $Exports<'@codemirror/state/dist'>;
}
declare module '@codemirror/state/dist/index.js' {
  declare module.exports: $Exports<'@codemirror/state/dist'>;
}
