// flow-typed signature: 85789ef276491f9c29a3891fe1eedc70
// flow-typed version: <<STUB>>/@codemirror/view_v^0.19.40/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@codemirror/view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@codemirror/view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@codemirror/view/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@codemirror/view/dist/index' {
  declare module.exports: $Exports<'@codemirror/view/dist'>;
}
declare module '@codemirror/view/dist/index.js' {
  declare module.exports: $Exports<'@codemirror/view/dist'>;
}
