// flow-typed signature: 73993bb890ce33f3a3ee3eb6409451e4
// flow-typed version: <<STUB>>/array-range_v^1.0.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'array-range'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'array-range' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'array-range/index' {
  declare module.exports: $Exports<'array-range'>;
}
declare module 'array-range/index.js' {
  declare module.exports: $Exports<'array-range'>;
}
