// flow-typed signature: 15027ec23a7de4cf3f20e202339bcdd2
// flow-typed version: <<STUB>>/array-move_v^1.0.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'array-move'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'array-move' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'array-move/index' {
  declare module.exports: $Exports<'array-move'>;
}
declare module 'array-move/index.js' {
  declare module.exports: $Exports<'array-move'>;
}
