// flow-typed signature: 514fab8c56ca0a23baab4b0312dadce2
// flow-typed version: <<STUB>>/bisection_v0.0.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bisection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bisection' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bisection/tests/bisection.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bisection/index' {
  declare module.exports: $Exports<'bisection'>;
}
declare module 'bisection/index.js' {
  declare module.exports: $Exports<'bisection'>;
}
declare module 'bisection/tests/bisection.test.js' {
  declare module.exports: $Exports<'bisection/tests/bisection.test'>;
}
