// flow-typed signature: a0055db752f740f032a365a1b93cb46c
// flow-typed version: <<STUB>>/devtools-license-check_v^0.2.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'devtools-license-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'devtools-license-check' {
  declare module.exports: any;
}
