// flow-typed signature: a7c70ab909632d739f8d9da70ff75ec7
// flow-typed version: <<STUB>>/fake-indexeddb_v^2.0.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fake-indexeddb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fake-indexeddb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fake-indexeddb/build/fakeIndexedDB' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/FDBCursor' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/FDBCursorWithValue' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/FDBDatabase' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/FDBFactory' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/FDBIndex' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/FDBKeyRange' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/FDBObjectStore' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/FDBOpenDBRequest' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/FDBRequest' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/FDBTransaction' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/FDBVersionChangeEvent' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/global' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/index' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/canInjectKey' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/cmp' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/Database' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/enforceRange' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/errors' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/extractKey' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/fakeDOMStringList' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/FakeEvent' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/FakeEventTarget' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/Index' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/KeyGenerator' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/ObjectStore' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/RecordStore' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/structuredClone' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/types' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/validateKeyPath' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/valueToKey' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/build/lib/valueToKeyRange' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBCursor' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBCursorWithValue' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBDatabase' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBFactory' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBIndex' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBKeyRange' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBObjectStore' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBOpenDBRequest' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBRequest' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBTransaction' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBVersionChangeEvent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fake-indexeddb/build/fakeIndexedDB.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/fakeIndexedDB'>;
}
declare module 'fake-indexeddb/build/FDBCursor.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/FDBCursor'>;
}
declare module 'fake-indexeddb/build/FDBCursorWithValue.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/FDBCursorWithValue'>;
}
declare module 'fake-indexeddb/build/FDBDatabase.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/FDBDatabase'>;
}
declare module 'fake-indexeddb/build/FDBFactory.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/FDBFactory'>;
}
declare module 'fake-indexeddb/build/FDBIndex.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/FDBIndex'>;
}
declare module 'fake-indexeddb/build/FDBKeyRange.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/FDBKeyRange'>;
}
declare module 'fake-indexeddb/build/FDBObjectStore.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/FDBObjectStore'>;
}
declare module 'fake-indexeddb/build/FDBOpenDBRequest.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/FDBOpenDBRequest'>;
}
declare module 'fake-indexeddb/build/FDBRequest.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/FDBRequest'>;
}
declare module 'fake-indexeddb/build/FDBTransaction.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/FDBTransaction'>;
}
declare module 'fake-indexeddb/build/FDBVersionChangeEvent.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/FDBVersionChangeEvent'>;
}
declare module 'fake-indexeddb/build/global.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/global'>;
}
declare module 'fake-indexeddb/build/index.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/index'>;
}
declare module 'fake-indexeddb/build/lib/canInjectKey.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/canInjectKey'>;
}
declare module 'fake-indexeddb/build/lib/cmp.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/cmp'>;
}
declare module 'fake-indexeddb/build/lib/Database.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/Database'>;
}
declare module 'fake-indexeddb/build/lib/enforceRange.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/enforceRange'>;
}
declare module 'fake-indexeddb/build/lib/errors.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/errors'>;
}
declare module 'fake-indexeddb/build/lib/extractKey.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/extractKey'>;
}
declare module 'fake-indexeddb/build/lib/fakeDOMStringList.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/fakeDOMStringList'>;
}
declare module 'fake-indexeddb/build/lib/FakeEvent.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/FakeEvent'>;
}
declare module 'fake-indexeddb/build/lib/FakeEventTarget.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/FakeEventTarget'>;
}
declare module 'fake-indexeddb/build/lib/Index.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/Index'>;
}
declare module 'fake-indexeddb/build/lib/KeyGenerator.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/KeyGenerator'>;
}
declare module 'fake-indexeddb/build/lib/ObjectStore.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/ObjectStore'>;
}
declare module 'fake-indexeddb/build/lib/RecordStore.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/RecordStore'>;
}
declare module 'fake-indexeddb/build/lib/structuredClone.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/structuredClone'>;
}
declare module 'fake-indexeddb/build/lib/types.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/types'>;
}
declare module 'fake-indexeddb/build/lib/validateKeyPath.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/validateKeyPath'>;
}
declare module 'fake-indexeddb/build/lib/valueToKey.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/valueToKey'>;
}
declare module 'fake-indexeddb/build/lib/valueToKeyRange.js' {
  declare module.exports: $Exports<'fake-indexeddb/build/lib/valueToKeyRange'>;
}
declare module 'fake-indexeddb/lib/FDBCursor.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBCursor'>;
}
declare module 'fake-indexeddb/lib/FDBCursorWithValue.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBCursorWithValue'>;
}
declare module 'fake-indexeddb/lib/FDBDatabase.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBDatabase'>;
}
declare module 'fake-indexeddb/lib/FDBFactory.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBFactory'>;
}
declare module 'fake-indexeddb/lib/FDBIndex.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBIndex'>;
}
declare module 'fake-indexeddb/lib/FDBKeyRange.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBKeyRange'>;
}
declare module 'fake-indexeddb/lib/FDBObjectStore.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBObjectStore'>;
}
declare module 'fake-indexeddb/lib/FDBOpenDBRequest.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBOpenDBRequest'>;
}
declare module 'fake-indexeddb/lib/FDBRequest.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBRequest'>;
}
declare module 'fake-indexeddb/lib/FDBTransaction.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBTransaction'>;
}
declare module 'fake-indexeddb/lib/FDBVersionChangeEvent.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBVersionChangeEvent'>;
}
