// flow-typed signature: 40fcfe46cbedcd0342c9ee88f6c6aa21
// flow-typed version: <<STUB>>/fetch-jsonp_v^1.0.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch-jsonp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fetch-jsonp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fetch-jsonp/build/fetch-jsonp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fetch-jsonp/build/fetch-jsonp.js' {
  declare module.exports: $Exports<'fetch-jsonp/build/fetch-jsonp'>;
}
