// flow-typed signature: b2b17857ee04ffe8573e660d7e77809e
// flow-typed version: <<STUB>>/local-web-server_v^1.2.6/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'local-web-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'local-web-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'local-web-server/bin/cli' {
  declare module.exports: any;
}

declare module 'local-web-server/example/mock-async/mocks/delayed' {
  declare module.exports: any;
}

declare module 'local-web-server/example/mock/mocks/five' {
  declare module.exports: any;
}

declare module 'local-web-server/example/mock/mocks/stream-self' {
  declare module.exports: any;
}

declare module 'local-web-server/example/mock/mocks/user' {
  declare module.exports: any;
}

declare module 'local-web-server/example/mock/mocks/users' {
  declare module.exports: any;
}

declare module 'local-web-server/lib/cli-options' {
  declare module.exports: any;
}

declare module 'local-web-server/lib/local-web-server' {
  declare module.exports: any;
}

declare module 'local-web-server/lib/middleware' {
  declare module.exports: any;
}

declare module 'local-web-server/test/rewrite-proxy' {
  declare module.exports: any;
}

declare module 'local-web-server/test/static' {
  declare module.exports: any;
}

declare module 'local-web-server/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'local-web-server/bin/cli.js' {
  declare module.exports: $Exports<'local-web-server/bin/cli'>;
}
declare module 'local-web-server/example/mock-async/mocks/delayed.js' {
  declare module.exports: $Exports<'local-web-server/example/mock-async/mocks/delayed'>;
}
declare module 'local-web-server/example/mock/mocks/five.js' {
  declare module.exports: $Exports<'local-web-server/example/mock/mocks/five'>;
}
declare module 'local-web-server/example/mock/mocks/stream-self.js' {
  declare module.exports: $Exports<'local-web-server/example/mock/mocks/stream-self'>;
}
declare module 'local-web-server/example/mock/mocks/user.js' {
  declare module.exports: $Exports<'local-web-server/example/mock/mocks/user'>;
}
declare module 'local-web-server/example/mock/mocks/users.js' {
  declare module.exports: $Exports<'local-web-server/example/mock/mocks/users'>;
}
declare module 'local-web-server/lib/cli-options.js' {
  declare module.exports: $Exports<'local-web-server/lib/cli-options'>;
}
declare module 'local-web-server/lib/local-web-server.js' {
  declare module.exports: $Exports<'local-web-server/lib/local-web-server'>;
}
declare module 'local-web-server/lib/middleware.js' {
  declare module.exports: $Exports<'local-web-server/lib/middleware'>;
}
declare module 'local-web-server/test/rewrite-proxy.js' {
  declare module.exports: $Exports<'local-web-server/test/rewrite-proxy'>;
}
declare module 'local-web-server/test/static.js' {
  declare module.exports: $Exports<'local-web-server/test/static'>;
}
declare module 'local-web-server/test/test.js' {
  declare module.exports: $Exports<'local-web-server/test/test'>;
}
