// flow-typed signature: 32e05d2fd8aef80563dbdd0573b6c58d
// flow-typed version: <<STUB>>/local-web-server_v^2.2.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'local-web-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'local-web-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'local-web-server/bin/cli' {
  declare module.exports: any;
}

declare module 'local-web-server/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'local-web-server/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'local-web-server/lib/cli-app' {
  declare module.exports: any;
}

declare module 'local-web-server/lib/command/middleware-list' {
  declare module.exports: any;
}

declare module 'local-web-server/lib/command/serve' {
  declare module.exports: any;
}

declare module 'local-web-server/lib/default-stack' {
  declare module.exports: any;
}

declare module 'local-web-server/lib/local-web-server' {
  declare module.exports: any;
}

declare module 'local-web-server/test/cli' {
  declare module.exports: any;
}

declare module 'local-web-server/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'local-web-server/bin/cli.js' {
  declare module.exports: $Exports<'local-web-server/bin/cli'>;
}
declare module 'local-web-server/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'local-web-server/coverage/lcov-report/prettify'>;
}
declare module 'local-web-server/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'local-web-server/coverage/lcov-report/sorter'>;
}
declare module 'local-web-server/lib/cli-app.js' {
  declare module.exports: $Exports<'local-web-server/lib/cli-app'>;
}
declare module 'local-web-server/lib/command/middleware-list.js' {
  declare module.exports: $Exports<'local-web-server/lib/command/middleware-list'>;
}
declare module 'local-web-server/lib/command/serve.js' {
  declare module.exports: $Exports<'local-web-server/lib/command/serve'>;
}
declare module 'local-web-server/lib/default-stack.js' {
  declare module.exports: $Exports<'local-web-server/lib/default-stack'>;
}
declare module 'local-web-server/lib/local-web-server.js' {
  declare module.exports: $Exports<'local-web-server/lib/local-web-server'>;
}
declare module 'local-web-server/test/cli.js' {
  declare module.exports: $Exports<'local-web-server/test/cli'>;
}
declare module 'local-web-server/test/test.js' {
  declare module.exports: $Exports<'local-web-server/test/test'>;
}
