// flow-typed signature: 350d4f91ad4105da89d9668bc85b4785
// flow-typed version: <<STUB>>/photon-colors_v1.0.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'photon-colors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'photon-colors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'photon-colors/build' {
  declare module.exports: any;
}

declare module 'photon-colors/colors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'photon-colors/build.js' {
  declare module.exports: $Exports<'photon-colors/build'>;
}
declare module 'photon-colors/colors.js' {
  declare module.exports: $Exports<'photon-colors/colors'>;
}
