// flow-typed signature: 1c09351e2e60d769d1f6e57d3b1ec0f2
// flow-typed version: <<STUB>>/react-contextmenu_v^2.6.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-contextmenu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-contextmenu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-contextmenu/dist/react-contextmenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/AbstractMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/actions' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/connectMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/ContextMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/ContextMenuTrigger' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/globalEventListener' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/helpers' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/index' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/MenuItem' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/SubMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/AbstractMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/actions' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/connectMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/ContextMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/ContextMenuTrigger' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/globalEventListener' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/helpers' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/index' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/MenuItem' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/SubMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/src/AbstractMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/src/actions' {
  declare module.exports: any;
}

declare module 'react-contextmenu/src/connectMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/src/ContextMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/src/ContextMenuTrigger' {
  declare module.exports: any;
}

declare module 'react-contextmenu/src/globalEventListener' {
  declare module.exports: any;
}

declare module 'react-contextmenu/src/helpers' {
  declare module.exports: any;
}

declare module 'react-contextmenu/src/index' {
  declare module.exports: any;
}

declare module 'react-contextmenu/src/MenuItem' {
  declare module.exports: any;
}

declare module 'react-contextmenu/src/SubMenu' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-contextmenu/dist/react-contextmenu.js' {
  declare module.exports: $Exports<'react-contextmenu/dist/react-contextmenu'>;
}
declare module 'react-contextmenu/es6/AbstractMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/AbstractMenu'>;
}
declare module 'react-contextmenu/es6/actions.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/actions'>;
}
declare module 'react-contextmenu/es6/connectMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/connectMenu'>;
}
declare module 'react-contextmenu/es6/ContextMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/ContextMenu'>;
}
declare module 'react-contextmenu/es6/ContextMenuTrigger.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/ContextMenuTrigger'>;
}
declare module 'react-contextmenu/es6/globalEventListener.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/globalEventListener'>;
}
declare module 'react-contextmenu/es6/helpers.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/helpers'>;
}
declare module 'react-contextmenu/es6/index.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/index'>;
}
declare module 'react-contextmenu/es6/MenuItem.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/MenuItem'>;
}
declare module 'react-contextmenu/es6/SubMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/SubMenu'>;
}
declare module 'react-contextmenu/modules/AbstractMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/AbstractMenu'>;
}
declare module 'react-contextmenu/modules/actions.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/actions'>;
}
declare module 'react-contextmenu/modules/connectMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/connectMenu'>;
}
declare module 'react-contextmenu/modules/ContextMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/ContextMenu'>;
}
declare module 'react-contextmenu/modules/ContextMenuTrigger.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/ContextMenuTrigger'>;
}
declare module 'react-contextmenu/modules/globalEventListener.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/globalEventListener'>;
}
declare module 'react-contextmenu/modules/helpers.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/helpers'>;
}
declare module 'react-contextmenu/modules/index.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/index'>;
}
declare module 'react-contextmenu/modules/MenuItem.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/MenuItem'>;
}
declare module 'react-contextmenu/modules/SubMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/SubMenu'>;
}
declare module 'react-contextmenu/src/AbstractMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/src/AbstractMenu'>;
}
declare module 'react-contextmenu/src/actions.js' {
  declare module.exports: $Exports<'react-contextmenu/src/actions'>;
}
declare module 'react-contextmenu/src/connectMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/src/connectMenu'>;
}
declare module 'react-contextmenu/src/ContextMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/src/ContextMenu'>;
}
declare module 'react-contextmenu/src/ContextMenuTrigger.js' {
  declare module.exports: $Exports<'react-contextmenu/src/ContextMenuTrigger'>;
}
declare module 'react-contextmenu/src/globalEventListener.js' {
  declare module.exports: $Exports<'react-contextmenu/src/globalEventListener'>;
}
declare module 'react-contextmenu/src/helpers.js' {
  declare module.exports: $Exports<'react-contextmenu/src/helpers'>;
}
declare module 'react-contextmenu/src/index.js' {
  declare module.exports: $Exports<'react-contextmenu/src/index'>;
}
declare module 'react-contextmenu/src/MenuItem.js' {
  declare module.exports: $Exports<'react-contextmenu/src/MenuItem'>;
}
declare module 'react-contextmenu/src/SubMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/src/SubMenu'>;
}
