// flow-typed signature: aa6464c5d4fb77ba388e15b2fa53a152
// flow-typed version: <<STUB>>/shallowequal_v^0.2.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shallowequal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'shallowequal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shallowequal/modules/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shallowequal/modules/index.js' {
  declare module.exports: $Exports<'shallowequal/modules/index'>;
}
