// flow-typed signature: efcbd73beabc21d795a62faaadb688fe
// flow-typed version: <<STUB>>/webworker_v0.8.4/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webworker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webworker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webworker/examples/prefork/master' {
  declare module.exports: any;
}

declare module 'webworker/examples/prefork/worker' {
  declare module.exports: any;
}

declare module 'webworker/lib/websocket-client' {
  declare module.exports: any;
}

declare module 'webworker/lib/webworker-child' {
  declare module.exports: any;
}

declare module 'webworker/lib/webworker-util' {
  declare module.exports: any;
}

declare module 'webworker/lib/webworker' {
  declare module.exports: any;
}

declare module 'webworker/lib/ws' {
  declare module.exports: any;
}

declare module 'webworker/lib/ws/connection' {
  declare module.exports: any;
}

declare module 'webworker/lib/ws/manager' {
  declare module.exports: any;
}

declare module 'webworker/test/test-error' {
  declare module.exports: any;
}

declare module 'webworker/test/test-fd' {
  declare module.exports: any;
}

declare module 'webworker/test/test-simple' {
  declare module.exports: any;
}

declare module 'webworker/test/workers/error' {
  declare module.exports: any;
}

declare module 'webworker/test/workers/fd' {
  declare module.exports: any;
}

declare module 'webworker/test/workers/simple' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webworker/examples/prefork/master.js' {
  declare module.exports: $Exports<'webworker/examples/prefork/master'>;
}
declare module 'webworker/examples/prefork/worker.js' {
  declare module.exports: $Exports<'webworker/examples/prefork/worker'>;
}
declare module 'webworker/lib/websocket-client.js' {
  declare module.exports: $Exports<'webworker/lib/websocket-client'>;
}
declare module 'webworker/lib/webworker-child.js' {
  declare module.exports: $Exports<'webworker/lib/webworker-child'>;
}
declare module 'webworker/lib/webworker-util.js' {
  declare module.exports: $Exports<'webworker/lib/webworker-util'>;
}
declare module 'webworker/lib/webworker.js' {
  declare module.exports: $Exports<'webworker/lib/webworker'>;
}
declare module 'webworker/lib/ws.js' {
  declare module.exports: $Exports<'webworker/lib/ws'>;
}
declare module 'webworker/lib/ws/connection.js' {
  declare module.exports: $Exports<'webworker/lib/ws/connection'>;
}
declare module 'webworker/lib/ws/manager.js' {
  declare module.exports: $Exports<'webworker/lib/ws/manager'>;
}
declare module 'webworker/test/test-error.js' {
  declare module.exports: $Exports<'webworker/test/test-error'>;
}
declare module 'webworker/test/test-fd.js' {
  declare module.exports: $Exports<'webworker/test/test-fd'>;
}
declare module 'webworker/test/test-simple.js' {
  declare module.exports: $Exports<'webworker/test/test-simple'>;
}
declare module 'webworker/test/workers/error.js' {
  declare module.exports: $Exports<'webworker/test/workers/error'>;
}
declare module 'webworker/test/workers/fd.js' {
  declare module.exports: $Exports<'webworker/test/workers/fd'>;
}
declare module 'webworker/test/workers/simple.js' {
  declare module.exports: $Exports<'webworker/test/workers/simple'>;
}
