// flow-typed signature: d95b1e40d6505e45f13bec2eb7644753
// flow-typed version: <<STUB>>/workerjs_vgithub:jasonLaster/workerjs/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'workerjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'workerjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'workerjs/bootstrap' {
  declare module.exports: any;
}

declare module 'workerjs/browser' {
  declare module.exports: any;
}

declare module 'workerjs/evalworker' {
  declare module.exports: any;
}

declare module 'workerjs/examples/app' {
  declare module.exports: any;
}

declare module 'workerjs/examples/bundle' {
  declare module.exports: any;
}

declare module 'workerjs/examples/evaltest' {
  declare module.exports: any;
}

declare module 'workerjs/examples/requiretest' {
  declare module.exports: any;
}

declare module 'workerjs/examples/worker' {
  declare module.exports: any;
}

declare module 'workerjs/requireworker' {
  declare module.exports: any;
}

declare module 'workerjs/test/eval' {
  declare module.exports: any;
}

declare module 'workerjs/test/fixtures/addEventListenerWorker' {
  declare module.exports: any;
}

declare module 'workerjs/test/fixtures/evalworker' {
  declare module.exports: any;
}

declare module 'workerjs/test/fixtures/exportsworker' {
  declare module.exports: any;
}

declare module 'workerjs/test/fixtures/fibworker' {
  declare module.exports: any;
}

declare module 'workerjs/test/fixtures/gammaworker' {
  declare module.exports: any;
}

declare module 'workerjs/test/fixtures/imported' {
  declare module.exports: any;
}

declare module 'workerjs/test/fixtures/pidworker' {
  declare module.exports: any;
}

declare module 'workerjs/test/fixtures/requireworker' {
  declare module.exports: any;
}

declare module 'workerjs/test/require' {
  declare module.exports: any;
}

// Filename aliases
declare module 'workerjs/bootstrap.js' {
  declare module.exports: $Exports<'workerjs/bootstrap'>;
}
declare module 'workerjs/browser.js' {
  declare module.exports: $Exports<'workerjs/browser'>;
}
declare module 'workerjs/evalworker.js' {
  declare module.exports: $Exports<'workerjs/evalworker'>;
}
declare module 'workerjs/examples/app.js' {
  declare module.exports: $Exports<'workerjs/examples/app'>;
}
declare module 'workerjs/examples/bundle.js' {
  declare module.exports: $Exports<'workerjs/examples/bundle'>;
}
declare module 'workerjs/examples/evaltest.js' {
  declare module.exports: $Exports<'workerjs/examples/evaltest'>;
}
declare module 'workerjs/examples/requiretest.js' {
  declare module.exports: $Exports<'workerjs/examples/requiretest'>;
}
declare module 'workerjs/examples/worker.js' {
  declare module.exports: $Exports<'workerjs/examples/worker'>;
}
declare module 'workerjs/index' {
  declare module.exports: $Exports<'workerjs'>;
}
declare module 'workerjs/index.js' {
  declare module.exports: $Exports<'workerjs'>;
}
declare module 'workerjs/requireworker.js' {
  declare module.exports: $Exports<'workerjs/requireworker'>;
}
declare module 'workerjs/test/eval.js' {
  declare module.exports: $Exports<'workerjs/test/eval'>;
}
declare module 'workerjs/test/fixtures/addEventListenerWorker.js' {
  declare module.exports: $Exports<'workerjs/test/fixtures/addEventListenerWorker'>;
}
declare module 'workerjs/test/fixtures/evalworker.js' {
  declare module.exports: $Exports<'workerjs/test/fixtures/evalworker'>;
}
declare module 'workerjs/test/fixtures/exportsworker.js' {
  declare module.exports: $Exports<'workerjs/test/fixtures/exportsworker'>;
}
declare module 'workerjs/test/fixtures/fibworker.js' {
  declare module.exports: $Exports<'workerjs/test/fixtures/fibworker'>;
}
declare module 'workerjs/test/fixtures/gammaworker.js' {
  declare module.exports: $Exports<'workerjs/test/fixtures/gammaworker'>;
}
declare module 'workerjs/test/fixtures/imported.js' {
  declare module.exports: $Exports<'workerjs/test/fixtures/imported'>;
}
declare module 'workerjs/test/fixtures/pidworker.js' {
  declare module.exports: $Exports<'workerjs/test/fixtures/pidworker'>;
}
declare module 'workerjs/test/fixtures/requireworker.js' {
  declare module.exports: $Exports<'workerjs/test/fixtures/requireworker'>;
}
declare module 'workerjs/test/require.js' {
  declare module.exports: $Exports<'workerjs/test/require'>;
}
