// flow-typed signature: cd33d60e2cb749449f5c2d918d136851
// flow-typed version: <<STUB>>/fetch-mock-jest_v1.5.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch-mock-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

// @flow
declare module '@fetch-mock/jest' {
  declare module.exports: any;
}
