// flow-typed signature: cd33d60e2cb749449f5c2d918d136851
// flow-typed version: <<STUB>>/fetch-mock-jest_v1.5.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch-mock-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

// @flow
declare module 'fetch-mock-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fetch-mock-jest/__tests__/jest-built-ins.spec' {
  declare module.exports: any;
}

declare module 'fetch-mock-jest/__tests__/jest-extensions-delete.spec' {
  declare module.exports: any;
}

declare module 'fetch-mock-jest/__tests__/jest-extensions-get.spec' {
  declare module.exports: any;
}

declare module 'fetch-mock-jest/__tests__/jest-extensions-head.spec' {
  declare module.exports: any;
}

declare module 'fetch-mock-jest/__tests__/jest-extensions-patch.spec' {
  declare module.exports: any;
}

declare module 'fetch-mock-jest/__tests__/jest-extensions-post.spec' {
  declare module.exports: any;
}

declare module 'fetch-mock-jest/__tests__/jest-extensions-put.spec' {
  declare module.exports: any;
}

declare module 'fetch-mock-jest/__tests__/jest-extensions.spec' {
  declare module.exports: any;
}

declare module 'fetch-mock-jest/__tests__/regressions.spec' {
  declare module.exports: any;
}

declare module 'fetch-mock-jest/browser' {
  declare module.exports: any;
}

declare module 'fetch-mock-jest/jest-extensions' {
  declare module.exports: any;
}

declare module 'fetch-mock-jest/jestify' {
  declare module.exports: any;
}

declare module 'fetch-mock-jest/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fetch-mock-jest/__tests__/jest-built-ins.spec.js' {
  declare module.exports: $Exports<'fetch-mock-jest/__tests__/jest-built-ins.spec'>;
}
declare module 'fetch-mock-jest/__tests__/jest-extensions-delete.spec.js' {
  declare module.exports: $Exports<'fetch-mock-jest/__tests__/jest-extensions-delete.spec'>;
}
declare module 'fetch-mock-jest/__tests__/jest-extensions-get.spec.js' {
  declare module.exports: $Exports<'fetch-mock-jest/__tests__/jest-extensions-get.spec'>;
}
declare module 'fetch-mock-jest/__tests__/jest-extensions-head.spec.js' {
  declare module.exports: $Exports<'fetch-mock-jest/__tests__/jest-extensions-head.spec'>;
}
declare module 'fetch-mock-jest/__tests__/jest-extensions-patch.spec.js' {
  declare module.exports: $Exports<'fetch-mock-jest/__tests__/jest-extensions-patch.spec'>;
}
declare module 'fetch-mock-jest/__tests__/jest-extensions-post.spec.js' {
  declare module.exports: $Exports<'fetch-mock-jest/__tests__/jest-extensions-post.spec'>;
}
declare module 'fetch-mock-jest/__tests__/jest-extensions-put.spec.js' {
  declare module.exports: $Exports<'fetch-mock-jest/__tests__/jest-extensions-put.spec'>;
}
declare module 'fetch-mock-jest/__tests__/jest-extensions.spec.js' {
  declare module.exports: $Exports<'fetch-mock-jest/__tests__/jest-extensions.spec'>;
}
declare module 'fetch-mock-jest/__tests__/regressions.spec.js' {
  declare module.exports: $Exports<'fetch-mock-jest/__tests__/regressions.spec'>;
}
declare module 'fetch-mock-jest/browser.js' {
  declare module.exports: $Exports<'fetch-mock-jest/browser'>;
}
declare module 'fetch-mock-jest/jest-extensions.js' {
  declare module.exports: $Exports<'fetch-mock-jest/jest-extensions'>;
}
declare module 'fetch-mock-jest/jestify.js' {
  declare module.exports: $Exports<'fetch-mock-jest/jestify'>;
}
declare module 'fetch-mock-jest/server.js' {
  declare module.exports: $Exports<'fetch-mock-jest/server'>;
}
