// flow-typed signature: 036f6a0f2be4b033aa53b08c6abd3c80
// flow-typed version: <<STUB>>/@fluent/langneg_v^0.5.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fluent/langneg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fluent/langneg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fluent/langneg/esm/accepted_languages' {
  declare module.exports: any;
}

declare module '@fluent/langneg/esm' {
  declare module.exports: any;
}

declare module '@fluent/langneg/esm/locale' {
  declare module.exports: any;
}

declare module '@fluent/langneg/esm/matches' {
  declare module.exports: any;
}

declare module '@fluent/langneg/esm/negotiate_languages' {
  declare module.exports: any;
}

declare module '@fluent/langneg/esm/subtags' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fluent/langneg/esm/accepted_languages.js' {
  declare module.exports: $Exports<'@fluent/langneg/esm/accepted_languages'>;
}
declare module '@fluent/langneg/esm/index' {
  declare module.exports: $Exports<'@fluent/langneg/esm'>;
}
declare module '@fluent/langneg/esm/index.js' {
  declare module.exports: $Exports<'@fluent/langneg/esm'>;
}
declare module '@fluent/langneg/esm/locale.js' {
  declare module.exports: $Exports<'@fluent/langneg/esm/locale'>;
}
declare module '@fluent/langneg/esm/matches.js' {
  declare module.exports: $Exports<'@fluent/langneg/esm/matches'>;
}
declare module '@fluent/langneg/esm/negotiate_languages.js' {
  declare module.exports: $Exports<'@fluent/langneg/esm/negotiate_languages'>;
}
declare module '@fluent/langneg/esm/subtags.js' {
  declare module.exports: $Exports<'@fluent/langneg/esm/subtags'>;
}
declare module '@fluent/langneg/index' {
  declare module.exports: $Exports<'@fluent/langneg'>;
}
declare module '@fluent/langneg/index.js' {
  declare module.exports: $Exports<'@fluent/langneg'>;
}
