// flow-typed signature: 75b6c46570b139108af96470ea08a91e
// flow-typed version: <<STUB>>/@fluent/react_v^0.13.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fluent/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fluent/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fluent/react/docs/_build/html/_static/doctools' {
  declare module.exports: any;
}

declare module '@fluent/react/docs/_build/html/_static/documentation_options' {
  declare module.exports: any;
}

declare module '@fluent/react/docs/_build/html/_static/jquery-3.4.1' {
  declare module.exports: any;
}

declare module '@fluent/react/docs/_build/html/_static/jquery' {
  declare module.exports: any;
}

declare module '@fluent/react/docs/_build/html/_static/language_data' {
  declare module.exports: any;
}

declare module '@fluent/react/docs/_build/html/_static/searchtools' {
  declare module.exports: any;
}

declare module '@fluent/react/docs/_build/html/_static/underscore-1.3.1' {
  declare module.exports: any;
}

declare module '@fluent/react/docs/_build/html/_static/underscore' {
  declare module.exports: any;
}

declare module '@fluent/react/docs/_build/html/searchindex' {
  declare module.exports: any;
}

declare module '@fluent/react/esm/context' {
  declare module.exports: any;
}

declare module '@fluent/react/esm' {
  declare module.exports: any;
}

declare module '@fluent/react/esm/localization' {
  declare module.exports: any;
}

declare module '@fluent/react/esm/localized' {
  declare module.exports: any;
}

declare module '@fluent/react/esm/markup' {
  declare module.exports: any;
}

declare module '@fluent/react/esm/provider' {
  declare module.exports: any;
}

declare module '@fluent/react/esm/use_localization' {
  declare module.exports: any;
}

declare module '@fluent/react/esm/with_localization' {
  declare module.exports: any;
}

declare module '@fluent/react/vendor/omittedCloseTags' {
  declare module.exports: any;
}

declare module '@fluent/react/vendor/voidElementTags' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fluent/react/docs/_build/html/_static/doctools.js' {
  declare module.exports: $Exports<'@fluent/react/docs/_build/html/_static/doctools'>;
}
declare module '@fluent/react/docs/_build/html/_static/documentation_options.js' {
  declare module.exports: $Exports<'@fluent/react/docs/_build/html/_static/documentation_options'>;
}
declare module '@fluent/react/docs/_build/html/_static/jquery-3.4.1.js' {
  declare module.exports: $Exports<'@fluent/react/docs/_build/html/_static/jquery-3.4.1'>;
}
declare module '@fluent/react/docs/_build/html/_static/jquery.js' {
  declare module.exports: $Exports<'@fluent/react/docs/_build/html/_static/jquery'>;
}
declare module '@fluent/react/docs/_build/html/_static/language_data.js' {
  declare module.exports: $Exports<'@fluent/react/docs/_build/html/_static/language_data'>;
}
declare module '@fluent/react/docs/_build/html/_static/searchtools.js' {
  declare module.exports: $Exports<'@fluent/react/docs/_build/html/_static/searchtools'>;
}
declare module '@fluent/react/docs/_build/html/_static/underscore-1.3.1.js' {
  declare module.exports: $Exports<'@fluent/react/docs/_build/html/_static/underscore-1.3.1'>;
}
declare module '@fluent/react/docs/_build/html/_static/underscore.js' {
  declare module.exports: $Exports<'@fluent/react/docs/_build/html/_static/underscore'>;
}
declare module '@fluent/react/docs/_build/html/searchindex.js' {
  declare module.exports: $Exports<'@fluent/react/docs/_build/html/searchindex'>;
}
declare module '@fluent/react/esm/context.js' {
  declare module.exports: $Exports<'@fluent/react/esm/context'>;
}
declare module '@fluent/react/esm/index' {
  declare module.exports: $Exports<'@fluent/react/esm'>;
}
declare module '@fluent/react/esm/index.js' {
  declare module.exports: $Exports<'@fluent/react/esm'>;
}
declare module '@fluent/react/esm/localization.js' {
  declare module.exports: $Exports<'@fluent/react/esm/localization'>;
}
declare module '@fluent/react/esm/localized.js' {
  declare module.exports: $Exports<'@fluent/react/esm/localized'>;
}
declare module '@fluent/react/esm/markup.js' {
  declare module.exports: $Exports<'@fluent/react/esm/markup'>;
}
declare module '@fluent/react/esm/provider.js' {
  declare module.exports: $Exports<'@fluent/react/esm/provider'>;
}
declare module '@fluent/react/esm/use_localization.js' {
  declare module.exports: $Exports<'@fluent/react/esm/use_localization'>;
}
declare module '@fluent/react/esm/with_localization.js' {
  declare module.exports: $Exports<'@fluent/react/esm/with_localization'>;
}
declare module '@fluent/react/index' {
  declare module.exports: $Exports<'@fluent/react'>;
}
declare module '@fluent/react/index.js' {
  declare module.exports: $Exports<'@fluent/react'>;
}
declare module '@fluent/react/vendor/omittedCloseTags.js' {
  declare module.exports: $Exports<'@fluent/react/vendor/omittedCloseTags'>;
}
declare module '@fluent/react/vendor/voidElementTags.js' {
  declare module.exports: $Exports<'@fluent/react/vendor/voidElementTags'>;
}
