// flow-typed signature: fe021f0c04dc3d314d57281fef425692
// flow-typed version: <<STUB>>/circular-dependency-plugin_v^5.0.2/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'circular-dependency-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'circular-dependency-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'circular-dependency-plugin/index' {
  declare module.exports: $Exports<'circular-dependency-plugin'>;
}
declare module 'circular-dependency-plugin/index.js' {
  declare module.exports: $Exports<'circular-dependency-plugin'>;
}
