// flow-typed signature: 6232c615491ee31636e7b1f87300825c
// flow-typed version: <<STUB>>/copy-webpack-plugin_v^6.1.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copy-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'copy-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'copy-webpack-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/postProcessPattern' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/preProcessPattern' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/processPattern' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/utils/createPatternGlob' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/utils/isTemplateLike' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/utils/promisify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'copy-webpack-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/cjs'>;
}
declare module 'copy-webpack-plugin/dist/index' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist'>;
}
declare module 'copy-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist'>;
}
declare module 'copy-webpack-plugin/dist/postProcessPattern.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/postProcessPattern'>;
}
declare module 'copy-webpack-plugin/dist/preProcessPattern.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/preProcessPattern'>;
}
declare module 'copy-webpack-plugin/dist/processPattern.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/processPattern'>;
}
declare module 'copy-webpack-plugin/dist/utils/createPatternGlob.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/utils/createPatternGlob'>;
}
declare module 'copy-webpack-plugin/dist/utils/isTemplateLike.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/utils/isTemplateLike'>;
}
declare module 'copy-webpack-plugin/dist/utils/promisify.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/utils/promisify'>;
}
