// flow-typed signature: 90c6c64e3037e924bb2645cf599b999d
// flow-typed version: <<STUB>>/devtools-license-check_v^0.8.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'devtools-license-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'devtools-license-check' {
  declare module.exports: any;
}
