// flow-typed signature: e4074ca084031df314a6aa5bb6f8c57c
// flow-typed version: <<STUB>>/devtools-license-check_v^0.7.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'devtools-license-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'devtools-license-check' {
  declare module.exports: any;
}
