// flow-typed signature: dcd31a0535ee4dd6477c3423b5426872
// flow-typed version: <<STUB>>/docsify-cli_v^4.4.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docsify-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'docsify-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docsify-cli/lib/cli' {
  declare module.exports: any;
}

declare module 'docsify-cli/lib/commands/init' {
  declare module.exports: any;
}

declare module 'docsify-cli/lib/commands/serve' {
  declare module.exports: any;
}

declare module 'docsify-cli/lib/commands/start' {
  declare module.exports: any;
}

declare module 'docsify-cli/lib' {
  declare module.exports: any;
}

declare module 'docsify-cli/lib/util' {
  declare module.exports: any;
}

declare module 'docsify-cli/tools/locales' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docsify-cli/lib/cli.js' {
  declare module.exports: $Exports<'docsify-cli/lib/cli'>;
}
declare module 'docsify-cli/lib/commands/init.js' {
  declare module.exports: $Exports<'docsify-cli/lib/commands/init'>;
}
declare module 'docsify-cli/lib/commands/serve.js' {
  declare module.exports: $Exports<'docsify-cli/lib/commands/serve'>;
}
declare module 'docsify-cli/lib/commands/start.js' {
  declare module.exports: $Exports<'docsify-cli/lib/commands/start'>;
}
declare module 'docsify-cli/lib/index' {
  declare module.exports: $Exports<'docsify-cli/lib'>;
}
declare module 'docsify-cli/lib/index.js' {
  declare module.exports: $Exports<'docsify-cli/lib'>;
}
declare module 'docsify-cli/lib/util/index' {
  declare module.exports: $Exports<'docsify-cli/lib/util'>;
}
declare module 'docsify-cli/lib/util/index.js' {
  declare module.exports: $Exports<'docsify-cli/lib/util'>;
}
declare module 'docsify-cli/tools/locales/index' {
  declare module.exports: $Exports<'docsify-cli/tools/locales'>;
}
declare module 'docsify-cli/tools/locales/index.js' {
  declare module.exports: $Exports<'docsify-cli/tools/locales'>;
}
