// flow-typed signature: e6f43a673a1ad489aea31817e5e11e45
// flow-typed version: <<STUB>>/gecko-profiler-demangle_v^0.1.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gecko-profiler-demangle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gecko-profiler-demangle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gecko-profiler-demangle/gecko_profiler_demangle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gecko-profiler-demangle/gecko_profiler_demangle.js' {
  declare module.exports: $Exports<'gecko-profiler-demangle/gecko_profiler_demangle'>;
}
