// flow-typed signature: 0766d7822509edd47b4df5712e52ba53
// flow-typed version: <<STUB>>/jest-environment-jsdom-thirteen_v^0.0.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-environment-jsdom-thirteen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-environment-jsdom-thirteen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-environment-jsdom-thirteen/build/index' {
  declare module.exports: any;
}

declare module 'jest-environment-jsdom-thirteen/types/Config' {
  declare module.exports: any;
}

declare module 'jest-environment-jsdom-thirteen/types/Console' {
  declare module.exports: any;
}

declare module 'jest-environment-jsdom-thirteen/types/Environment' {
  declare module.exports: any;
}

declare module 'jest-environment-jsdom-thirteen/types/Global' {
  declare module.exports: any;
}

declare module 'jest-environment-jsdom-thirteen/types/Reporters' {
  declare module.exports: any;
}

declare module 'jest-environment-jsdom-thirteen/types/TestResult' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-environment-jsdom-thirteen/build/index.js' {
  declare module.exports: $Exports<'jest-environment-jsdom-thirteen/build/index'>;
}
declare module 'jest-environment-jsdom-thirteen/types/Config.js' {
  declare module.exports: $Exports<'jest-environment-jsdom-thirteen/types/Config'>;
}
declare module 'jest-environment-jsdom-thirteen/types/Console.js' {
  declare module.exports: $Exports<'jest-environment-jsdom-thirteen/types/Console'>;
}
declare module 'jest-environment-jsdom-thirteen/types/Environment.js' {
  declare module.exports: $Exports<'jest-environment-jsdom-thirteen/types/Environment'>;
}
declare module 'jest-environment-jsdom-thirteen/types/Global.js' {
  declare module.exports: $Exports<'jest-environment-jsdom-thirteen/types/Global'>;
}
declare module 'jest-environment-jsdom-thirteen/types/Reporters.js' {
  declare module.exports: $Exports<'jest-environment-jsdom-thirteen/types/Reporters'>;
}
declare module 'jest-environment-jsdom-thirteen/types/TestResult.js' {
  declare module.exports: $Exports<'jest-environment-jsdom-thirteen/types/TestResult'>;
}
