// flow-typed signature: 1c028d08245b4177e0b403668f5c8792
// flow-typed version: <<STUB>>/local-web-server_v^4.2.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'local-web-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'local-web-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'local-web-server/bin/cli' {
  declare module.exports: any;
}

declare module 'local-web-server/lib/cli-app' {
  declare module.exports: any;
}

declare module 'local-web-server/lib/default-stack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'local-web-server/bin/cli.js' {
  declare module.exports: $Exports<'local-web-server/bin/cli'>;
}
declare module 'local-web-server/index' {
  declare module.exports: $Exports<'local-web-server'>;
}
declare module 'local-web-server/index.js' {
  declare module.exports: $Exports<'local-web-server'>;
}
declare module 'local-web-server/lib/cli-app.js' {
  declare module.exports: $Exports<'local-web-server/lib/cli-app'>;
}
declare module 'local-web-server/lib/default-stack.js' {
  declare module.exports: $Exports<'local-web-server/lib/default-stack'>;
}
