// flow-typed signature: 1be3250cdb108f3929b2361bb4401d13
// flow-typed version: <<STUB>>/lockfile-lint_v^4.3.7/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lockfile-lint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lockfile-lint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lockfile-lint/bin/lockfile-lint' {
  declare module.exports: any;
}

declare module 'lockfile-lint/src/config' {
  declare module.exports: any;
}

declare module 'lockfile-lint/src/main' {
  declare module.exports: any;
}

declare module 'lockfile-lint/src/validators' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lockfile-lint/bin/lockfile-lint.js' {
  declare module.exports: $Exports<'lockfile-lint/bin/lockfile-lint'>;
}
declare module 'lockfile-lint/src/config.js' {
  declare module.exports: $Exports<'lockfile-lint/src/config'>;
}
declare module 'lockfile-lint/src/main.js' {
  declare module.exports: $Exports<'lockfile-lint/src/main'>;
}
declare module 'lockfile-lint/src/validators/index' {
  declare module.exports: $Exports<'lockfile-lint/src/validators'>;
}
declare module 'lockfile-lint/src/validators/index.js' {
  declare module.exports: $Exports<'lockfile-lint/src/validators'>;
}
