// flow-typed signature: aad389e7f5e0949f7b259f8d2e86295f
// flow-typed version: <<STUB>>/lodash.clonedeep_v^4.5.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.clonedeep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.clonedeep' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.clonedeep/index' {
  declare module.exports: $Exports<'lodash.clonedeep'>;
}
declare module 'lodash.clonedeep/index.js' {
  declare module.exports: $Exports<'lodash.clonedeep'>;
}
