// flow-typed signature: 897603f548d324f28a1fa20c34211191
// flow-typed version: <<STUB>>/long_v^5.2.3/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'long'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'long' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'long/umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'long/index' {
  declare module.exports: $Exports<'long'>;
}
declare module 'long/index.js' {
  declare module.exports: $Exports<'long'>;
}
declare module 'long/umd/index' {
  declare module.exports: $Exports<'long/umd'>;
}
declare module 'long/umd/index.js' {
  declare module.exports: $Exports<'long/umd'>;
}
