// flow-typed signature: 6ea9f766ab617f8c6b05d99b0402a38b
// flow-typed version: <<STUB>>/memoize-immutable_v^3.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'memoize-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'memoize-immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'memoize-immutable/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'memoize-immutable/__tests__/test-is-optimized' {
  declare module.exports: any;
}

declare module 'memoize-immutable/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'memoize-immutable/__tests__/index.test.js' {
  declare module.exports: $Exports<'memoize-immutable/__tests__/index.test'>;
}
declare module 'memoize-immutable/__tests__/test-is-optimized.js' {
  declare module.exports: $Exports<'memoize-immutable/__tests__/test-is-optimized'>;
}
declare module 'memoize-immutable/dist/index.js' {
  declare module.exports: $Exports<'memoize-immutable/dist/index'>;
}
declare module 'memoize-immutable/index' {
  declare module.exports: $Exports<'memoize-immutable'>;
}
declare module 'memoize-immutable/index.js' {
  declare module.exports: $Exports<'memoize-immutable'>;
}
