// flow-typed signature: f19ddd5e19e18568825a925ab4efb5d7
// flow-typed version: <<STUB>>/mixedtuplemap_v1.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mixedtuplemap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mixedtuplemap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mixedtuplemap/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'mixedtuplemap/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mixedtuplemap/__tests__/index.test.js' {
  declare module.exports: $Exports<'mixedtuplemap/__tests__/index.test'>;
}
declare module 'mixedtuplemap/dist/index.js' {
  declare module.exports: $Exports<'mixedtuplemap/dist/index'>;
}
declare module 'mixedtuplemap/index' {
  declare module.exports: $Exports<'mixedtuplemap'>;
}
declare module 'mixedtuplemap/index.js' {
  declare module.exports: $Exports<'mixedtuplemap'>;
}
