// flow-typed signature: 361dd6f30fce4db6f1a1c5fce17798f3
// flow-typed version: <<STUB>>/mixedtuplemap_v^1.0.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mixedtuplemap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mixedtuplemap' {
  export class MixedTupleMap<K, V> {
    constructor();
    toString(): string;
    has(tuple: K): boolean;
    set(tuple: K, value: V);
    get(tuple: K): V;
    clear();
  }

  export default MixedTupleMap;
}
