// flow-typed signature: 06b456186acd950235c631c20c230d8d
// flow-typed version: <<STUB>>/namedtuplemap_v^1.0.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'namedtuplemap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'namedtuplemap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'namedtuplemap/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'namedtuplemap/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'namedtuplemap/__tests__/index.test.js' {
  declare module.exports: $Exports<'namedtuplemap/__tests__/index.test'>;
}
declare module 'namedtuplemap/dist/index' {
  declare module.exports: $Exports<'namedtuplemap/dist'>;
}
declare module 'namedtuplemap/dist/index.js' {
  declare module.exports: $Exports<'namedtuplemap/dist'>;
}
declare module 'namedtuplemap/index' {
  declare module.exports: $Exports<'namedtuplemap'>;
}
declare module 'namedtuplemap/index.js' {
  declare module.exports: $Exports<'namedtuplemap'>;
}
