// flow-typed signature: 2ab1b85afe7408ea7d9e09a714e6f14d
// flow-typed version: <<STUB>>/pako_v~1.0.2/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pako'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pako' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pako/dist/pako_deflate' {
  declare module.exports: any;
}

declare module 'pako/dist/pako_deflate.min' {
  declare module.exports: any;
}

declare module 'pako/dist/pako_inflate' {
  declare module.exports: any;
}

declare module 'pako/dist/pako_inflate.min' {
  declare module.exports: any;
}

declare module 'pako/dist/pako' {
  declare module.exports: any;
}

declare module 'pako/dist/pako.min' {
  declare module.exports: any;
}

declare module 'pako/lib/deflate' {
  declare module.exports: any;
}

declare module 'pako/lib/inflate' {
  declare module.exports: any;
}

declare module 'pako/lib/utils/common' {
  declare module.exports: any;
}

declare module 'pako/lib/utils/strings' {
  declare module.exports: any;
}

declare module 'pako/lib/zlib/adler32' {
  declare module.exports: any;
}

declare module 'pako/lib/zlib/constants' {
  declare module.exports: any;
}

declare module 'pako/lib/zlib/crc32' {
  declare module.exports: any;
}

declare module 'pako/lib/zlib/deflate' {
  declare module.exports: any;
}

declare module 'pako/lib/zlib/gzheader' {
  declare module.exports: any;
}

declare module 'pako/lib/zlib/inffast' {
  declare module.exports: any;
}

declare module 'pako/lib/zlib/inflate' {
  declare module.exports: any;
}

declare module 'pako/lib/zlib/inftrees' {
  declare module.exports: any;
}

declare module 'pako/lib/zlib/messages' {
  declare module.exports: any;
}

declare module 'pako/lib/zlib/trees' {
  declare module.exports: any;
}

declare module 'pako/lib/zlib/zstream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pako/dist/pako_deflate.js' {
  declare module.exports: $Exports<'pako/dist/pako_deflate'>;
}
declare module 'pako/dist/pako_deflate.min.js' {
  declare module.exports: $Exports<'pako/dist/pako_deflate.min'>;
}
declare module 'pako/dist/pako_inflate.js' {
  declare module.exports: $Exports<'pako/dist/pako_inflate'>;
}
declare module 'pako/dist/pako_inflate.min.js' {
  declare module.exports: $Exports<'pako/dist/pako_inflate.min'>;
}
declare module 'pako/dist/pako.js' {
  declare module.exports: $Exports<'pako/dist/pako'>;
}
declare module 'pako/dist/pako.min.js' {
  declare module.exports: $Exports<'pako/dist/pako.min'>;
}
declare module 'pako/index' {
  declare module.exports: $Exports<'pako'>;
}
declare module 'pako/index.js' {
  declare module.exports: $Exports<'pako'>;
}
declare module 'pako/lib/deflate.js' {
  declare module.exports: $Exports<'pako/lib/deflate'>;
}
declare module 'pako/lib/inflate.js' {
  declare module.exports: $Exports<'pako/lib/inflate'>;
}
declare module 'pako/lib/utils/common.js' {
  declare module.exports: $Exports<'pako/lib/utils/common'>;
}
declare module 'pako/lib/utils/strings.js' {
  declare module.exports: $Exports<'pako/lib/utils/strings'>;
}
declare module 'pako/lib/zlib/adler32.js' {
  declare module.exports: $Exports<'pako/lib/zlib/adler32'>;
}
declare module 'pako/lib/zlib/constants.js' {
  declare module.exports: $Exports<'pako/lib/zlib/constants'>;
}
declare module 'pako/lib/zlib/crc32.js' {
  declare module.exports: $Exports<'pako/lib/zlib/crc32'>;
}
declare module 'pako/lib/zlib/deflate.js' {
  declare module.exports: $Exports<'pako/lib/zlib/deflate'>;
}
declare module 'pako/lib/zlib/gzheader.js' {
  declare module.exports: $Exports<'pako/lib/zlib/gzheader'>;
}
declare module 'pako/lib/zlib/inffast.js' {
  declare module.exports: $Exports<'pako/lib/zlib/inffast'>;
}
declare module 'pako/lib/zlib/inflate.js' {
  declare module.exports: $Exports<'pako/lib/zlib/inflate'>;
}
declare module 'pako/lib/zlib/inftrees.js' {
  declare module.exports: $Exports<'pako/lib/zlib/inftrees'>;
}
declare module 'pako/lib/zlib/messages.js' {
  declare module.exports: $Exports<'pako/lib/zlib/messages'>;
}
declare module 'pako/lib/zlib/trees.js' {
  declare module.exports: $Exports<'pako/lib/zlib/trees'>;
}
declare module 'pako/lib/zlib/zstream.js' {
  declare module.exports: $Exports<'pako/lib/zlib/zstream'>;
}
