// flow-typed signature: be16dcb4e8bf716ec2cc496e8a012ae5
// flow-typed version: <<STUB>>/react-intersection-observer_v^8.32.2/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intersection-observer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intersection-observer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intersection-observer/react-intersection-observer.esm' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/react-intersection-observer' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/react-intersection-observer.m' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/react-intersection-observer.umd' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/test-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intersection-observer/react-intersection-observer.esm.js' {
  declare module.exports: $Exports<'react-intersection-observer/react-intersection-observer.esm'>;
}
declare module 'react-intersection-observer/react-intersection-observer.js' {
  declare module.exports: $Exports<'react-intersection-observer/react-intersection-observer'>;
}
declare module 'react-intersection-observer/react-intersection-observer.m.js' {
  declare module.exports: $Exports<'react-intersection-observer/react-intersection-observer.m'>;
}
declare module 'react-intersection-observer/react-intersection-observer.umd.js' {
  declare module.exports: $Exports<'react-intersection-observer/react-intersection-observer.umd'>;
}
declare module 'react-intersection-observer/test-utils.js' {
  declare module.exports: $Exports<'react-intersection-observer/test-utils'>;
}
