// flow-typed signature: c54b09ac762bb9d74637382aa9db61db
// flow-typed version: <<STUB>>/react-dom_v^16.8.6/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dom/cjs/react-dom-server.browser.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-server.browser.production.min' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-server.node.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-server.node.production.min' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-test-utils.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-test-utils.production.min' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-unstable-fizz.browser.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-unstable-fizz.browser.production.min' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-unstable-fizz.node.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-unstable-fizz.node.production.min' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-unstable-native-dependencies.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-unstable-native-dependencies.production.min' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom.production.min' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom.profiling.min' {
  declare module.exports: any;
}

declare module 'react-dom/profiling' {
  declare module.exports: any;
}

declare module 'react-dom/server.browser' {
  declare module.exports: any;
}

declare module 'react-dom/server' {
  declare module.exports: any;
}

declare module 'react-dom/server.node' {
  declare module.exports: any;
}

declare module 'react-dom/test-utils' {
  declare module.exports: any;
}

declare module 'react-dom/umd/react-dom-server.browser.development' {
  declare module.exports: any;
}

declare module 'react-dom/umd/react-dom-server.browser.production.min' {
  declare module.exports: any;
}

declare module 'react-dom/umd/react-dom-test-utils.development' {
  declare module.exports: any;
}

declare module 'react-dom/umd/react-dom-test-utils.production.min' {
  declare module.exports: any;
}

declare module 'react-dom/umd/react-dom-unstable-fizz.browser.development' {
  declare module.exports: any;
}

declare module 'react-dom/umd/react-dom-unstable-fizz.browser.production.min' {
  declare module.exports: any;
}

declare module 'react-dom/umd/react-dom-unstable-native-dependencies.development' {
  declare module.exports: any;
}

declare module 'react-dom/umd/react-dom-unstable-native-dependencies.production.min' {
  declare module.exports: any;
}

declare module 'react-dom/umd/react-dom.development' {
  declare module.exports: any;
}

declare module 'react-dom/umd/react-dom.production.min' {
  declare module.exports: any;
}

declare module 'react-dom/umd/react-dom.profiling.min' {
  declare module.exports: any;
}

declare module 'react-dom/unstable-fizz.browser' {
  declare module.exports: any;
}

declare module 'react-dom/unstable-fizz' {
  declare module.exports: any;
}

declare module 'react-dom/unstable-fizz.node' {
  declare module.exports: any;
}

declare module 'react-dom/unstable-native-dependencies' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dom/cjs/react-dom-server.browser.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-server.browser.development'>;
}
declare module 'react-dom/cjs/react-dom-server.browser.production.min.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-server.browser.production.min'>;
}
declare module 'react-dom/cjs/react-dom-server.node.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-server.node.development'>;
}
declare module 'react-dom/cjs/react-dom-server.node.production.min.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-server.node.production.min'>;
}
declare module 'react-dom/cjs/react-dom-test-utils.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-test-utils.development'>;
}
declare module 'react-dom/cjs/react-dom-test-utils.production.min.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-test-utils.production.min'>;
}
declare module 'react-dom/cjs/react-dom-unstable-fizz.browser.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-unstable-fizz.browser.development'>;
}
declare module 'react-dom/cjs/react-dom-unstable-fizz.browser.production.min.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-unstable-fizz.browser.production.min'>;
}
declare module 'react-dom/cjs/react-dom-unstable-fizz.node.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-unstable-fizz.node.development'>;
}
declare module 'react-dom/cjs/react-dom-unstable-fizz.node.production.min.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-unstable-fizz.node.production.min'>;
}
declare module 'react-dom/cjs/react-dom-unstable-native-dependencies.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-unstable-native-dependencies.development'>;
}
declare module 'react-dom/cjs/react-dom-unstable-native-dependencies.production.min.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-unstable-native-dependencies.production.min'>;
}
declare module 'react-dom/cjs/react-dom.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom.development'>;
}
declare module 'react-dom/cjs/react-dom.production.min.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom.production.min'>;
}
declare module 'react-dom/cjs/react-dom.profiling.min.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom.profiling.min'>;
}
declare module 'react-dom/index' {
  declare module.exports: $Exports<'react-dom'>;
}
declare module 'react-dom/index.js' {
  declare module.exports: $Exports<'react-dom'>;
}
declare module 'react-dom/profiling.js' {
  declare module.exports: $Exports<'react-dom/profiling'>;
}
declare module 'react-dom/server.browser.js' {
  declare module.exports: $Exports<'react-dom/server.browser'>;
}
declare module 'react-dom/server.js' {
  declare module.exports: $Exports<'react-dom/server'>;
}
declare module 'react-dom/server.node.js' {
  declare module.exports: $Exports<'react-dom/server.node'>;
}
declare module 'react-dom/test-utils.js' {
  declare module.exports: $Exports<'react-dom/test-utils'>;
}
declare module 'react-dom/umd/react-dom-server.browser.development.js' {
  declare module.exports: $Exports<'react-dom/umd/react-dom-server.browser.development'>;
}
declare module 'react-dom/umd/react-dom-server.browser.production.min.js' {
  declare module.exports: $Exports<'react-dom/umd/react-dom-server.browser.production.min'>;
}
declare module 'react-dom/umd/react-dom-test-utils.development.js' {
  declare module.exports: $Exports<'react-dom/umd/react-dom-test-utils.development'>;
}
declare module 'react-dom/umd/react-dom-test-utils.production.min.js' {
  declare module.exports: $Exports<'react-dom/umd/react-dom-test-utils.production.min'>;
}
declare module 'react-dom/umd/react-dom-unstable-fizz.browser.development.js' {
  declare module.exports: $Exports<'react-dom/umd/react-dom-unstable-fizz.browser.development'>;
}
declare module 'react-dom/umd/react-dom-unstable-fizz.browser.production.min.js' {
  declare module.exports: $Exports<'react-dom/umd/react-dom-unstable-fizz.browser.production.min'>;
}
declare module 'react-dom/umd/react-dom-unstable-native-dependencies.development.js' {
  declare module.exports: $Exports<'react-dom/umd/react-dom-unstable-native-dependencies.development'>;
}
declare module 'react-dom/umd/react-dom-unstable-native-dependencies.production.min.js' {
  declare module.exports: $Exports<'react-dom/umd/react-dom-unstable-native-dependencies.production.min'>;
}
declare module 'react-dom/umd/react-dom.development.js' {
  declare module.exports: $Exports<'react-dom/umd/react-dom.development'>;
}
declare module 'react-dom/umd/react-dom.production.min.js' {
  declare module.exports: $Exports<'react-dom/umd/react-dom.production.min'>;
}
declare module 'react-dom/umd/react-dom.profiling.min.js' {
  declare module.exports: $Exports<'react-dom/umd/react-dom.profiling.min'>;
}
declare module 'react-dom/unstable-fizz.browser.js' {
  declare module.exports: $Exports<'react-dom/unstable-fizz.browser'>;
}
declare module 'react-dom/unstable-fizz.js' {
  declare module.exports: $Exports<'react-dom/unstable-fizz'>;
}
declare module 'react-dom/unstable-fizz.node.js' {
  declare module.exports: $Exports<'react-dom/unstable-fizz.node'>;
}
declare module 'react-dom/unstable-native-dependencies.js' {
  declare module.exports: $Exports<'react-dom/unstable-native-dependencies'>;
}
