// flow-typed signature: 464955ec56003cfbb67da117ffa1e870
// flow-typed version: <<STUB>>/react-transition-group_v^4.4.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-transition-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-transition-group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-transition-group/cjs/config' {
  declare module.exports: any;
}

declare module 'react-transition-group/cjs/CSSTransition' {
  declare module.exports: any;
}

declare module 'react-transition-group/cjs' {
  declare module.exports: any;
}

declare module 'react-transition-group/cjs/ReplaceTransition' {
  declare module.exports: any;
}

declare module 'react-transition-group/cjs/SwitchTransition' {
  declare module.exports: any;
}

declare module 'react-transition-group/cjs/Transition' {
  declare module.exports: any;
}

declare module 'react-transition-group/cjs/TransitionGroup' {
  declare module.exports: any;
}

declare module 'react-transition-group/cjs/TransitionGroupContext' {
  declare module.exports: any;
}

declare module 'react-transition-group/cjs/utils/ChildMapping' {
  declare module.exports: any;
}

declare module 'react-transition-group/cjs/utils/PropTypes' {
  declare module.exports: any;
}

declare module 'react-transition-group/cjs/utils/SimpleSet' {
  declare module.exports: any;
}

declare module 'react-transition-group/dist/react-transition-group' {
  declare module.exports: any;
}

declare module 'react-transition-group/dist/react-transition-group.min' {
  declare module.exports: any;
}

declare module 'react-transition-group/esm/config' {
  declare module.exports: any;
}

declare module 'react-transition-group/esm/CSSTransition' {
  declare module.exports: any;
}

declare module 'react-transition-group/esm' {
  declare module.exports: any;
}

declare module 'react-transition-group/esm/ReplaceTransition' {
  declare module.exports: any;
}

declare module 'react-transition-group/esm/SwitchTransition' {
  declare module.exports: any;
}

declare module 'react-transition-group/esm/Transition' {
  declare module.exports: any;
}

declare module 'react-transition-group/esm/TransitionGroup' {
  declare module.exports: any;
}

declare module 'react-transition-group/esm/TransitionGroupContext' {
  declare module.exports: any;
}

declare module 'react-transition-group/esm/utils/ChildMapping' {
  declare module.exports: any;
}

declare module 'react-transition-group/esm/utils/PropTypes' {
  declare module.exports: any;
}

declare module 'react-transition-group/esm/utils/SimpleSet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-transition-group/cjs/config.js' {
  declare module.exports: $Exports<'react-transition-group/cjs/config'>;
}
declare module 'react-transition-group/cjs/CSSTransition.js' {
  declare module.exports: $Exports<'react-transition-group/cjs/CSSTransition'>;
}
declare module 'react-transition-group/cjs/index' {
  declare module.exports: $Exports<'react-transition-group/cjs'>;
}
declare module 'react-transition-group/cjs/index.js' {
  declare module.exports: $Exports<'react-transition-group/cjs'>;
}
declare module 'react-transition-group/cjs/ReplaceTransition.js' {
  declare module.exports: $Exports<'react-transition-group/cjs/ReplaceTransition'>;
}
declare module 'react-transition-group/cjs/SwitchTransition.js' {
  declare module.exports: $Exports<'react-transition-group/cjs/SwitchTransition'>;
}
declare module 'react-transition-group/cjs/Transition.js' {
  declare module.exports: $Exports<'react-transition-group/cjs/Transition'>;
}
declare module 'react-transition-group/cjs/TransitionGroup.js' {
  declare module.exports: $Exports<'react-transition-group/cjs/TransitionGroup'>;
}
declare module 'react-transition-group/cjs/TransitionGroupContext.js' {
  declare module.exports: $Exports<'react-transition-group/cjs/TransitionGroupContext'>;
}
declare module 'react-transition-group/cjs/utils/ChildMapping.js' {
  declare module.exports: $Exports<'react-transition-group/cjs/utils/ChildMapping'>;
}
declare module 'react-transition-group/cjs/utils/PropTypes.js' {
  declare module.exports: $Exports<'react-transition-group/cjs/utils/PropTypes'>;
}
declare module 'react-transition-group/cjs/utils/SimpleSet.js' {
  declare module.exports: $Exports<'react-transition-group/cjs/utils/SimpleSet'>;
}
declare module 'react-transition-group/dist/react-transition-group.js' {
  declare module.exports: $Exports<'react-transition-group/dist/react-transition-group'>;
}
declare module 'react-transition-group/dist/react-transition-group.min.js' {
  declare module.exports: $Exports<'react-transition-group/dist/react-transition-group.min'>;
}
declare module 'react-transition-group/esm/config.js' {
  declare module.exports: $Exports<'react-transition-group/esm/config'>;
}
declare module 'react-transition-group/esm/CSSTransition.js' {
  declare module.exports: $Exports<'react-transition-group/esm/CSSTransition'>;
}
declare module 'react-transition-group/esm/index' {
  declare module.exports: $Exports<'react-transition-group/esm'>;
}
declare module 'react-transition-group/esm/index.js' {
  declare module.exports: $Exports<'react-transition-group/esm'>;
}
declare module 'react-transition-group/esm/ReplaceTransition.js' {
  declare module.exports: $Exports<'react-transition-group/esm/ReplaceTransition'>;
}
declare module 'react-transition-group/esm/SwitchTransition.js' {
  declare module.exports: $Exports<'react-transition-group/esm/SwitchTransition'>;
}
declare module 'react-transition-group/esm/Transition.js' {
  declare module.exports: $Exports<'react-transition-group/esm/Transition'>;
}
declare module 'react-transition-group/esm/TransitionGroup.js' {
  declare module.exports: $Exports<'react-transition-group/esm/TransitionGroup'>;
}
declare module 'react-transition-group/esm/TransitionGroupContext.js' {
  declare module.exports: $Exports<'react-transition-group/esm/TransitionGroupContext'>;
}
declare module 'react-transition-group/esm/utils/ChildMapping.js' {
  declare module.exports: $Exports<'react-transition-group/esm/utils/ChildMapping'>;
}
declare module 'react-transition-group/esm/utils/PropTypes.js' {
  declare module.exports: $Exports<'react-transition-group/esm/utils/PropTypes'>;
}
declare module 'react-transition-group/esm/utils/SimpleSet.js' {
  declare module.exports: $Exports<'react-transition-group/esm/utils/SimpleSet'>;
}
