// flow-typed signature: f78b23d3d3b1775ce768e83bfbc62ab6
// flow-typed version: <<STUB>>/react-splitter-layout_v^3.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-splitter-layout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-splitter-layout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-splitter-layout/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-splitter-layout/lib/index.js' {
  declare module.exports: $Exports<'react-splitter-layout/lib/index'>;
}
