// flow-typed signature: d7f72ffd8c003005de5e4ccece23be4b
// flow-typed version: <<STUB>>/react-contextmenu_v~2.14.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-contextmenu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-contextmenu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-contextmenu/dist/react-contextmenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/AbstractMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/actions' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/connectMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/ContextMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/ContextMenuTrigger' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/globalEventListener' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/helpers' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/MenuItem' {
  declare module.exports: any;
}

declare module 'react-contextmenu/es6/SubMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/AbstractMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/actions' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/connectMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/ContextMenu' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/ContextMenuTrigger' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/globalEventListener' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/helpers' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/MenuItem' {
  declare module.exports: any;
}

declare module 'react-contextmenu/modules/SubMenu' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-contextmenu/dist/react-contextmenu.js' {
  declare module.exports: $Exports<'react-contextmenu/dist/react-contextmenu'>;
}
declare module 'react-contextmenu/es6/AbstractMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/AbstractMenu'>;
}
declare module 'react-contextmenu/es6/actions.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/actions'>;
}
declare module 'react-contextmenu/es6/connectMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/connectMenu'>;
}
declare module 'react-contextmenu/es6/ContextMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/ContextMenu'>;
}
declare module 'react-contextmenu/es6/ContextMenuTrigger.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/ContextMenuTrigger'>;
}
declare module 'react-contextmenu/es6/globalEventListener.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/globalEventListener'>;
}
declare module 'react-contextmenu/es6/helpers.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/helpers'>;
}
declare module 'react-contextmenu/es6/index' {
  declare module.exports: $Exports<'react-contextmenu/es6'>;
}
declare module 'react-contextmenu/es6/index.js' {
  declare module.exports: $Exports<'react-contextmenu/es6'>;
}
declare module 'react-contextmenu/es6/MenuItem.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/MenuItem'>;
}
declare module 'react-contextmenu/es6/SubMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/es6/SubMenu'>;
}
declare module 'react-contextmenu/modules/AbstractMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/AbstractMenu'>;
}
declare module 'react-contextmenu/modules/actions.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/actions'>;
}
declare module 'react-contextmenu/modules/connectMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/connectMenu'>;
}
declare module 'react-contextmenu/modules/ContextMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/ContextMenu'>;
}
declare module 'react-contextmenu/modules/ContextMenuTrigger.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/ContextMenuTrigger'>;
}
declare module 'react-contextmenu/modules/globalEventListener.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/globalEventListener'>;
}
declare module 'react-contextmenu/modules/helpers.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/helpers'>;
}
declare module 'react-contextmenu/modules/index' {
  declare module.exports: $Exports<'react-contextmenu/modules'>;
}
declare module 'react-contextmenu/modules/index.js' {
  declare module.exports: $Exports<'react-contextmenu/modules'>;
}
declare module 'react-contextmenu/modules/MenuItem.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/MenuItem'>;
}
declare module 'react-contextmenu/modules/SubMenu.js' {
  declare module.exports: $Exports<'react-contextmenu/modules/SubMenu'>;
}
