// flow-typed signature: a3ef90bfbace13fef307570c5a61ed3d
// flow-typed version: <<STUB>>/react-axe_v^3.2.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-axe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-axe' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-axe/index' {
  declare module.exports: $Exports<'react-axe'>;
}
declare module 'react-axe/index.js' {
  declare module.exports: $Exports<'react-axe'>;
}
