// flow-typed signature: 940b368817e12506eb633daf1fe8662f
// flow-typed version: <<STUB>>/refractor_v^4.1.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'refractor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'refractor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'refractor/lang/abap' {
  declare module.exports: any;
}

declare module 'refractor/lang/abnf' {
  declare module.exports: any;
}

declare module 'refractor/lang/actionscript' {
  declare module.exports: any;
}

declare module 'refractor/lang/ada' {
  declare module.exports: any;
}

declare module 'refractor/lang/agda' {
  declare module.exports: any;
}

declare module 'refractor/lang/al' {
  declare module.exports: any;
}

declare module 'refractor/lang/antlr4' {
  declare module.exports: any;
}

declare module 'refractor/lang/apacheconf' {
  declare module.exports: any;
}

declare module 'refractor/lang/apex' {
  declare module.exports: any;
}

declare module 'refractor/lang/apl' {
  declare module.exports: any;
}

declare module 'refractor/lang/applescript' {
  declare module.exports: any;
}

declare module 'refractor/lang/aql' {
  declare module.exports: any;
}

declare module 'refractor/lang/arduino' {
  declare module.exports: any;
}

declare module 'refractor/lang/arff' {
  declare module.exports: any;
}

declare module 'refractor/lang/asciidoc' {
  declare module.exports: any;
}

declare module 'refractor/lang/asm6502' {
  declare module.exports: any;
}

declare module 'refractor/lang/aspnet' {
  declare module.exports: any;
}

declare module 'refractor/lang/autohotkey' {
  declare module.exports: any;
}

declare module 'refractor/lang/autoit' {
  declare module.exports: any;
}

declare module 'refractor/lang/bash' {
  declare module.exports: any;
}

declare module 'refractor/lang/basic' {
  declare module.exports: any;
}

declare module 'refractor/lang/batch' {
  declare module.exports: any;
}

declare module 'refractor/lang/bbcode' {
  declare module.exports: any;
}

declare module 'refractor/lang/birb' {
  declare module.exports: any;
}

declare module 'refractor/lang/bison' {
  declare module.exports: any;
}

declare module 'refractor/lang/bnf' {
  declare module.exports: any;
}

declare module 'refractor/lang/brainfuck' {
  declare module.exports: any;
}

declare module 'refractor/lang/brightscript' {
  declare module.exports: any;
}

declare module 'refractor/lang/bro' {
  declare module.exports: any;
}

declare module 'refractor/lang/bsl' {
  declare module.exports: any;
}

declare module 'refractor/lang/c' {
  declare module.exports: any;
}

declare module 'refractor/lang/cfscript' {
  declare module.exports: any;
}

declare module 'refractor/lang/chaiscript' {
  declare module.exports: any;
}

declare module 'refractor/lang/cil' {
  declare module.exports: any;
}

declare module 'refractor/lang/clike' {
  declare module.exports: any;
}

declare module 'refractor/lang/clojure' {
  declare module.exports: any;
}

declare module 'refractor/lang/cmake' {
  declare module.exports: any;
}

declare module 'refractor/lang/cobol' {
  declare module.exports: any;
}

declare module 'refractor/lang/coffeescript' {
  declare module.exports: any;
}

declare module 'refractor/lang/concurnas' {
  declare module.exports: any;
}

declare module 'refractor/lang/coq' {
  declare module.exports: any;
}

declare module 'refractor/lang/cpp' {
  declare module.exports: any;
}

declare module 'refractor/lang/crystal' {
  declare module.exports: any;
}

declare module 'refractor/lang/csharp' {
  declare module.exports: any;
}

declare module 'refractor/lang/csp' {
  declare module.exports: any;
}

declare module 'refractor/lang/css-extras' {
  declare module.exports: any;
}

declare module 'refractor/lang/css' {
  declare module.exports: any;
}

declare module 'refractor/lang/csv' {
  declare module.exports: any;
}

declare module 'refractor/lang/cypher' {
  declare module.exports: any;
}

declare module 'refractor/lang/d' {
  declare module.exports: any;
}

declare module 'refractor/lang/dart' {
  declare module.exports: any;
}

declare module 'refractor/lang/dataweave' {
  declare module.exports: any;
}

declare module 'refractor/lang/dax' {
  declare module.exports: any;
}

declare module 'refractor/lang/dhall' {
  declare module.exports: any;
}

declare module 'refractor/lang/diff' {
  declare module.exports: any;
}

declare module 'refractor/lang/django' {
  declare module.exports: any;
}

declare module 'refractor/lang/dns-zone-file' {
  declare module.exports: any;
}

declare module 'refractor/lang/docker' {
  declare module.exports: any;
}

declare module 'refractor/lang/dot' {
  declare module.exports: any;
}

declare module 'refractor/lang/ebnf' {
  declare module.exports: any;
}

declare module 'refractor/lang/editorconfig' {
  declare module.exports: any;
}

declare module 'refractor/lang/eiffel' {
  declare module.exports: any;
}

declare module 'refractor/lang/ejs' {
  declare module.exports: any;
}

declare module 'refractor/lang/elixir' {
  declare module.exports: any;
}

declare module 'refractor/lang/elm' {
  declare module.exports: any;
}

declare module 'refractor/lang/erb' {
  declare module.exports: any;
}

declare module 'refractor/lang/erlang' {
  declare module.exports: any;
}

declare module 'refractor/lang/etlua' {
  declare module.exports: any;
}

declare module 'refractor/lang/excel-formula' {
  declare module.exports: any;
}

declare module 'refractor/lang/factor' {
  declare module.exports: any;
}

declare module 'refractor/lang/false' {
  declare module.exports: any;
}

declare module 'refractor/lang/firestore-security-rules' {
  declare module.exports: any;
}

declare module 'refractor/lang/flow' {
  declare module.exports: any;
}

declare module 'refractor/lang/fortran' {
  declare module.exports: any;
}

declare module 'refractor/lang/fsharp' {
  declare module.exports: any;
}

declare module 'refractor/lang/ftl' {
  declare module.exports: any;
}

declare module 'refractor/lang/gcode' {
  declare module.exports: any;
}

declare module 'refractor/lang/gdscript' {
  declare module.exports: any;
}

declare module 'refractor/lang/gedcom' {
  declare module.exports: any;
}

declare module 'refractor/lang/gherkin' {
  declare module.exports: any;
}

declare module 'refractor/lang/git' {
  declare module.exports: any;
}

declare module 'refractor/lang/glsl' {
  declare module.exports: any;
}

declare module 'refractor/lang/gml' {
  declare module.exports: any;
}

declare module 'refractor/lang/go' {
  declare module.exports: any;
}

declare module 'refractor/lang/graphql' {
  declare module.exports: any;
}

declare module 'refractor/lang/groovy' {
  declare module.exports: any;
}

declare module 'refractor/lang/haml' {
  declare module.exports: any;
}

declare module 'refractor/lang/handlebars' {
  declare module.exports: any;
}

declare module 'refractor/lang/haskell' {
  declare module.exports: any;
}

declare module 'refractor/lang/haxe' {
  declare module.exports: any;
}

declare module 'refractor/lang/hcl' {
  declare module.exports: any;
}

declare module 'refractor/lang/hlsl' {
  declare module.exports: any;
}

declare module 'refractor/lang/hpkp' {
  declare module.exports: any;
}

declare module 'refractor/lang/hsts' {
  declare module.exports: any;
}

declare module 'refractor/lang/http' {
  declare module.exports: any;
}

declare module 'refractor/lang/ichigojam' {
  declare module.exports: any;
}

declare module 'refractor/lang/icon' {
  declare module.exports: any;
}

declare module 'refractor/lang/icu-message-format' {
  declare module.exports: any;
}

declare module 'refractor/lang/idris' {
  declare module.exports: any;
}

declare module 'refractor/lang/iecst' {
  declare module.exports: any;
}

declare module 'refractor/lang/ignore' {
  declare module.exports: any;
}

declare module 'refractor/lang/inform7' {
  declare module.exports: any;
}

declare module 'refractor/lang/ini' {
  declare module.exports: any;
}

declare module 'refractor/lang/io' {
  declare module.exports: any;
}

declare module 'refractor/lang/j' {
  declare module.exports: any;
}

declare module 'refractor/lang/java' {
  declare module.exports: any;
}

declare module 'refractor/lang/javadoc' {
  declare module.exports: any;
}

declare module 'refractor/lang/javadoclike' {
  declare module.exports: any;
}

declare module 'refractor/lang/javascript' {
  declare module.exports: any;
}

declare module 'refractor/lang/javastacktrace' {
  declare module.exports: any;
}

declare module 'refractor/lang/jexl' {
  declare module.exports: any;
}

declare module 'refractor/lang/jolie' {
  declare module.exports: any;
}

declare module 'refractor/lang/jq' {
  declare module.exports: any;
}

declare module 'refractor/lang/js-extras' {
  declare module.exports: any;
}

declare module 'refractor/lang/js-templates' {
  declare module.exports: any;
}

declare module 'refractor/lang/jsdoc' {
  declare module.exports: any;
}

declare module 'refractor/lang/json' {
  declare module.exports: any;
}

declare module 'refractor/lang/json5' {
  declare module.exports: any;
}

declare module 'refractor/lang/jsonp' {
  declare module.exports: any;
}

declare module 'refractor/lang/jsstacktrace' {
  declare module.exports: any;
}

declare module 'refractor/lang/jsx' {
  declare module.exports: any;
}

declare module 'refractor/lang/julia' {
  declare module.exports: any;
}

declare module 'refractor/lang/keyman' {
  declare module.exports: any;
}

declare module 'refractor/lang/kotlin' {
  declare module.exports: any;
}

declare module 'refractor/lang/kumir' {
  declare module.exports: any;
}

declare module 'refractor/lang/latex' {
  declare module.exports: any;
}

declare module 'refractor/lang/latte' {
  declare module.exports: any;
}

declare module 'refractor/lang/less' {
  declare module.exports: any;
}

declare module 'refractor/lang/lilypond' {
  declare module.exports: any;
}

declare module 'refractor/lang/liquid' {
  declare module.exports: any;
}

declare module 'refractor/lang/lisp' {
  declare module.exports: any;
}

declare module 'refractor/lang/livescript' {
  declare module.exports: any;
}

declare module 'refractor/lang/llvm' {
  declare module.exports: any;
}

declare module 'refractor/lang/log' {
  declare module.exports: any;
}

declare module 'refractor/lang/lolcode' {
  declare module.exports: any;
}

declare module 'refractor/lang/lua' {
  declare module.exports: any;
}

declare module 'refractor/lang/makefile' {
  declare module.exports: any;
}

declare module 'refractor/lang/markdown' {
  declare module.exports: any;
}

declare module 'refractor/lang/markup-templating' {
  declare module.exports: any;
}

declare module 'refractor/lang/markup' {
  declare module.exports: any;
}

declare module 'refractor/lang/matlab' {
  declare module.exports: any;
}

declare module 'refractor/lang/mel' {
  declare module.exports: any;
}

declare module 'refractor/lang/mizar' {
  declare module.exports: any;
}

declare module 'refractor/lang/mongodb' {
  declare module.exports: any;
}

declare module 'refractor/lang/monkey' {
  declare module.exports: any;
}

declare module 'refractor/lang/moonscript' {
  declare module.exports: any;
}

declare module 'refractor/lang/n1ql' {
  declare module.exports: any;
}

declare module 'refractor/lang/n4js' {
  declare module.exports: any;
}

declare module 'refractor/lang/nand2tetris-hdl' {
  declare module.exports: any;
}

declare module 'refractor/lang/naniscript' {
  declare module.exports: any;
}

declare module 'refractor/lang/nasm' {
  declare module.exports: any;
}

declare module 'refractor/lang/neon' {
  declare module.exports: any;
}

declare module 'refractor/lang/nevod' {
  declare module.exports: any;
}

declare module 'refractor/lang/nginx' {
  declare module.exports: any;
}

declare module 'refractor/lang/nim' {
  declare module.exports: any;
}

declare module 'refractor/lang/nix' {
  declare module.exports: any;
}

declare module 'refractor/lang/nsis' {
  declare module.exports: any;
}

declare module 'refractor/lang/objectivec' {
  declare module.exports: any;
}

declare module 'refractor/lang/ocaml' {
  declare module.exports: any;
}

declare module 'refractor/lang/opencl' {
  declare module.exports: any;
}

declare module 'refractor/lang/openqasm' {
  declare module.exports: any;
}

declare module 'refractor/lang/oz' {
  declare module.exports: any;
}

declare module 'refractor/lang/parigp' {
  declare module.exports: any;
}

declare module 'refractor/lang/parser' {
  declare module.exports: any;
}

declare module 'refractor/lang/pascal' {
  declare module.exports: any;
}

declare module 'refractor/lang/pascaligo' {
  declare module.exports: any;
}

declare module 'refractor/lang/pcaxis' {
  declare module.exports: any;
}

declare module 'refractor/lang/peoplecode' {
  declare module.exports: any;
}

declare module 'refractor/lang/perl' {
  declare module.exports: any;
}

declare module 'refractor/lang/php-extras' {
  declare module.exports: any;
}

declare module 'refractor/lang/php' {
  declare module.exports: any;
}

declare module 'refractor/lang/phpdoc' {
  declare module.exports: any;
}

declare module 'refractor/lang/plsql' {
  declare module.exports: any;
}

declare module 'refractor/lang/powerquery' {
  declare module.exports: any;
}

declare module 'refractor/lang/powershell' {
  declare module.exports: any;
}

declare module 'refractor/lang/processing' {
  declare module.exports: any;
}

declare module 'refractor/lang/prolog' {
  declare module.exports: any;
}

declare module 'refractor/lang/promql' {
  declare module.exports: any;
}

declare module 'refractor/lang/properties' {
  declare module.exports: any;
}

declare module 'refractor/lang/protobuf' {
  declare module.exports: any;
}

declare module 'refractor/lang/psl' {
  declare module.exports: any;
}

declare module 'refractor/lang/pug' {
  declare module.exports: any;
}

declare module 'refractor/lang/puppet' {
  declare module.exports: any;
}

declare module 'refractor/lang/pure' {
  declare module.exports: any;
}

declare module 'refractor/lang/purebasic' {
  declare module.exports: any;
}

declare module 'refractor/lang/purescript' {
  declare module.exports: any;
}

declare module 'refractor/lang/python' {
  declare module.exports: any;
}

declare module 'refractor/lang/q' {
  declare module.exports: any;
}

declare module 'refractor/lang/qml' {
  declare module.exports: any;
}

declare module 'refractor/lang/qore' {
  declare module.exports: any;
}

declare module 'refractor/lang/qsharp' {
  declare module.exports: any;
}

declare module 'refractor/lang/r' {
  declare module.exports: any;
}

declare module 'refractor/lang/racket' {
  declare module.exports: any;
}

declare module 'refractor/lang/reason' {
  declare module.exports: any;
}

declare module 'refractor/lang/regex' {
  declare module.exports: any;
}

declare module 'refractor/lang/rego' {
  declare module.exports: any;
}

declare module 'refractor/lang/renpy' {
  declare module.exports: any;
}

declare module 'refractor/lang/rest' {
  declare module.exports: any;
}

declare module 'refractor/lang/rip' {
  declare module.exports: any;
}

declare module 'refractor/lang/roboconf' {
  declare module.exports: any;
}

declare module 'refractor/lang/robotframework' {
  declare module.exports: any;
}

declare module 'refractor/lang/ruby' {
  declare module.exports: any;
}

declare module 'refractor/lang/rust' {
  declare module.exports: any;
}

declare module 'refractor/lang/sas' {
  declare module.exports: any;
}

declare module 'refractor/lang/sass' {
  declare module.exports: any;
}

declare module 'refractor/lang/scala' {
  declare module.exports: any;
}

declare module 'refractor/lang/scheme' {
  declare module.exports: any;
}

declare module 'refractor/lang/scss' {
  declare module.exports: any;
}

declare module 'refractor/lang/shell-session' {
  declare module.exports: any;
}

declare module 'refractor/lang/smali' {
  declare module.exports: any;
}

declare module 'refractor/lang/smalltalk' {
  declare module.exports: any;
}

declare module 'refractor/lang/smarty' {
  declare module.exports: any;
}

declare module 'refractor/lang/sml' {
  declare module.exports: any;
}

declare module 'refractor/lang/solidity' {
  declare module.exports: any;
}

declare module 'refractor/lang/solution-file' {
  declare module.exports: any;
}

declare module 'refractor/lang/soy' {
  declare module.exports: any;
}

declare module 'refractor/lang/sparql' {
  declare module.exports: any;
}

declare module 'refractor/lang/splunk-spl' {
  declare module.exports: any;
}

declare module 'refractor/lang/sqf' {
  declare module.exports: any;
}

declare module 'refractor/lang/sql' {
  declare module.exports: any;
}

declare module 'refractor/lang/squirrel' {
  declare module.exports: any;
}

declare module 'refractor/lang/stan' {
  declare module.exports: any;
}

declare module 'refractor/lang/stylus' {
  declare module.exports: any;
}

declare module 'refractor/lang/swift' {
  declare module.exports: any;
}

declare module 'refractor/lang/t4-cs' {
  declare module.exports: any;
}

declare module 'refractor/lang/t4-templating' {
  declare module.exports: any;
}

declare module 'refractor/lang/t4-vb' {
  declare module.exports: any;
}

declare module 'refractor/lang/tap' {
  declare module.exports: any;
}

declare module 'refractor/lang/tcl' {
  declare module.exports: any;
}

declare module 'refractor/lang/textile' {
  declare module.exports: any;
}

declare module 'refractor/lang/toml' {
  declare module.exports: any;
}

declare module 'refractor/lang/tsx' {
  declare module.exports: any;
}

declare module 'refractor/lang/tt2' {
  declare module.exports: any;
}

declare module 'refractor/lang/turtle' {
  declare module.exports: any;
}

declare module 'refractor/lang/twig' {
  declare module.exports: any;
}

declare module 'refractor/lang/typescript' {
  declare module.exports: any;
}

declare module 'refractor/lang/typoscript' {
  declare module.exports: any;
}

declare module 'refractor/lang/unrealscript' {
  declare module.exports: any;
}

declare module 'refractor/lang/uri' {
  declare module.exports: any;
}

declare module 'refractor/lang/v' {
  declare module.exports: any;
}

declare module 'refractor/lang/vala' {
  declare module.exports: any;
}

declare module 'refractor/lang/vbnet' {
  declare module.exports: any;
}

declare module 'refractor/lang/velocity' {
  declare module.exports: any;
}

declare module 'refractor/lang/verilog' {
  declare module.exports: any;
}

declare module 'refractor/lang/vhdl' {
  declare module.exports: any;
}

declare module 'refractor/lang/vim' {
  declare module.exports: any;
}

declare module 'refractor/lang/visual-basic' {
  declare module.exports: any;
}

declare module 'refractor/lang/warpscript' {
  declare module.exports: any;
}

declare module 'refractor/lang/wasm' {
  declare module.exports: any;
}

declare module 'refractor/lang/wiki' {
  declare module.exports: any;
}

declare module 'refractor/lang/wolfram' {
  declare module.exports: any;
}

declare module 'refractor/lang/xeora' {
  declare module.exports: any;
}

declare module 'refractor/lang/xml-doc' {
  declare module.exports: any;
}

declare module 'refractor/lang/xojo' {
  declare module.exports: any;
}

declare module 'refractor/lang/xquery' {
  declare module.exports: any;
}

declare module 'refractor/lang/yaml' {
  declare module.exports: any;
}

declare module 'refractor/lang/yang' {
  declare module.exports: any;
}

declare module 'refractor/lang/zig' {
  declare module.exports: any;
}

declare module 'refractor/lib/all' {
  declare module.exports: any;
}

declare module 'refractor/lib/common' {
  declare module.exports: any;
}

declare module 'refractor/lib/core' {
  declare module.exports: any;
}

// Filename aliases
declare module 'refractor/index' {
  declare module.exports: $Exports<'refractor'>;
}
declare module 'refractor/index.js' {
  declare module.exports: $Exports<'refractor'>;
}
declare module 'refractor/lang/abap.js' {
  declare module.exports: $Exports<'refractor/lang/abap'>;
}
declare module 'refractor/lang/abnf.js' {
  declare module.exports: $Exports<'refractor/lang/abnf'>;
}
declare module 'refractor/lang/actionscript.js' {
  declare module.exports: $Exports<'refractor/lang/actionscript'>;
}
declare module 'refractor/lang/ada.js' {
  declare module.exports: $Exports<'refractor/lang/ada'>;
}
declare module 'refractor/lang/agda.js' {
  declare module.exports: $Exports<'refractor/lang/agda'>;
}
declare module 'refractor/lang/al.js' {
  declare module.exports: $Exports<'refractor/lang/al'>;
}
declare module 'refractor/lang/antlr4.js' {
  declare module.exports: $Exports<'refractor/lang/antlr4'>;
}
declare module 'refractor/lang/apacheconf.js' {
  declare module.exports: $Exports<'refractor/lang/apacheconf'>;
}
declare module 'refractor/lang/apex.js' {
  declare module.exports: $Exports<'refractor/lang/apex'>;
}
declare module 'refractor/lang/apl.js' {
  declare module.exports: $Exports<'refractor/lang/apl'>;
}
declare module 'refractor/lang/applescript.js' {
  declare module.exports: $Exports<'refractor/lang/applescript'>;
}
declare module 'refractor/lang/aql.js' {
  declare module.exports: $Exports<'refractor/lang/aql'>;
}
declare module 'refractor/lang/arduino.js' {
  declare module.exports: $Exports<'refractor/lang/arduino'>;
}
declare module 'refractor/lang/arff.js' {
  declare module.exports: $Exports<'refractor/lang/arff'>;
}
declare module 'refractor/lang/asciidoc.js' {
  declare module.exports: $Exports<'refractor/lang/asciidoc'>;
}
declare module 'refractor/lang/asm6502.js' {
  declare module.exports: $Exports<'refractor/lang/asm6502'>;
}
declare module 'refractor/lang/aspnet.js' {
  declare module.exports: $Exports<'refractor/lang/aspnet'>;
}
declare module 'refractor/lang/autohotkey.js' {
  declare module.exports: $Exports<'refractor/lang/autohotkey'>;
}
declare module 'refractor/lang/autoit.js' {
  declare module.exports: $Exports<'refractor/lang/autoit'>;
}
declare module 'refractor/lang/bash.js' {
  declare module.exports: $Exports<'refractor/lang/bash'>;
}
declare module 'refractor/lang/basic.js' {
  declare module.exports: $Exports<'refractor/lang/basic'>;
}
declare module 'refractor/lang/batch.js' {
  declare module.exports: $Exports<'refractor/lang/batch'>;
}
declare module 'refractor/lang/bbcode.js' {
  declare module.exports: $Exports<'refractor/lang/bbcode'>;
}
declare module 'refractor/lang/birb.js' {
  declare module.exports: $Exports<'refractor/lang/birb'>;
}
declare module 'refractor/lang/bison.js' {
  declare module.exports: $Exports<'refractor/lang/bison'>;
}
declare module 'refractor/lang/bnf.js' {
  declare module.exports: $Exports<'refractor/lang/bnf'>;
}
declare module 'refractor/lang/brainfuck.js' {
  declare module.exports: $Exports<'refractor/lang/brainfuck'>;
}
declare module 'refractor/lang/brightscript.js' {
  declare module.exports: $Exports<'refractor/lang/brightscript'>;
}
declare module 'refractor/lang/bro.js' {
  declare module.exports: $Exports<'refractor/lang/bro'>;
}
declare module 'refractor/lang/bsl.js' {
  declare module.exports: $Exports<'refractor/lang/bsl'>;
}
declare module 'refractor/lang/c.js' {
  declare module.exports: $Exports<'refractor/lang/c'>;
}
declare module 'refractor/lang/cfscript.js' {
  declare module.exports: $Exports<'refractor/lang/cfscript'>;
}
declare module 'refractor/lang/chaiscript.js' {
  declare module.exports: $Exports<'refractor/lang/chaiscript'>;
}
declare module 'refractor/lang/cil.js' {
  declare module.exports: $Exports<'refractor/lang/cil'>;
}
declare module 'refractor/lang/clike.js' {
  declare module.exports: $Exports<'refractor/lang/clike'>;
}
declare module 'refractor/lang/clojure.js' {
  declare module.exports: $Exports<'refractor/lang/clojure'>;
}
declare module 'refractor/lang/cmake.js' {
  declare module.exports: $Exports<'refractor/lang/cmake'>;
}
declare module 'refractor/lang/cobol.js' {
  declare module.exports: $Exports<'refractor/lang/cobol'>;
}
declare module 'refractor/lang/coffeescript.js' {
  declare module.exports: $Exports<'refractor/lang/coffeescript'>;
}
declare module 'refractor/lang/concurnas.js' {
  declare module.exports: $Exports<'refractor/lang/concurnas'>;
}
declare module 'refractor/lang/coq.js' {
  declare module.exports: $Exports<'refractor/lang/coq'>;
}
declare module 'refractor/lang/cpp.js' {
  declare module.exports: $Exports<'refractor/lang/cpp'>;
}
declare module 'refractor/lang/crystal.js' {
  declare module.exports: $Exports<'refractor/lang/crystal'>;
}
declare module 'refractor/lang/csharp.js' {
  declare module.exports: $Exports<'refractor/lang/csharp'>;
}
declare module 'refractor/lang/csp.js' {
  declare module.exports: $Exports<'refractor/lang/csp'>;
}
declare module 'refractor/lang/css-extras.js' {
  declare module.exports: $Exports<'refractor/lang/css-extras'>;
}
declare module 'refractor/lang/css.js' {
  declare module.exports: $Exports<'refractor/lang/css'>;
}
declare module 'refractor/lang/csv.js' {
  declare module.exports: $Exports<'refractor/lang/csv'>;
}
declare module 'refractor/lang/cypher.js' {
  declare module.exports: $Exports<'refractor/lang/cypher'>;
}
declare module 'refractor/lang/d.js' {
  declare module.exports: $Exports<'refractor/lang/d'>;
}
declare module 'refractor/lang/dart.js' {
  declare module.exports: $Exports<'refractor/lang/dart'>;
}
declare module 'refractor/lang/dataweave.js' {
  declare module.exports: $Exports<'refractor/lang/dataweave'>;
}
declare module 'refractor/lang/dax.js' {
  declare module.exports: $Exports<'refractor/lang/dax'>;
}
declare module 'refractor/lang/dhall.js' {
  declare module.exports: $Exports<'refractor/lang/dhall'>;
}
declare module 'refractor/lang/diff.js' {
  declare module.exports: $Exports<'refractor/lang/diff'>;
}
declare module 'refractor/lang/django.js' {
  declare module.exports: $Exports<'refractor/lang/django'>;
}
declare module 'refractor/lang/dns-zone-file.js' {
  declare module.exports: $Exports<'refractor/lang/dns-zone-file'>;
}
declare module 'refractor/lang/docker.js' {
  declare module.exports: $Exports<'refractor/lang/docker'>;
}
declare module 'refractor/lang/dot.js' {
  declare module.exports: $Exports<'refractor/lang/dot'>;
}
declare module 'refractor/lang/ebnf.js' {
  declare module.exports: $Exports<'refractor/lang/ebnf'>;
}
declare module 'refractor/lang/editorconfig.js' {
  declare module.exports: $Exports<'refractor/lang/editorconfig'>;
}
declare module 'refractor/lang/eiffel.js' {
  declare module.exports: $Exports<'refractor/lang/eiffel'>;
}
declare module 'refractor/lang/ejs.js' {
  declare module.exports: $Exports<'refractor/lang/ejs'>;
}
declare module 'refractor/lang/elixir.js' {
  declare module.exports: $Exports<'refractor/lang/elixir'>;
}
declare module 'refractor/lang/elm.js' {
  declare module.exports: $Exports<'refractor/lang/elm'>;
}
declare module 'refractor/lang/erb.js' {
  declare module.exports: $Exports<'refractor/lang/erb'>;
}
declare module 'refractor/lang/erlang.js' {
  declare module.exports: $Exports<'refractor/lang/erlang'>;
}
declare module 'refractor/lang/etlua.js' {
  declare module.exports: $Exports<'refractor/lang/etlua'>;
}
declare module 'refractor/lang/excel-formula.js' {
  declare module.exports: $Exports<'refractor/lang/excel-formula'>;
}
declare module 'refractor/lang/factor.js' {
  declare module.exports: $Exports<'refractor/lang/factor'>;
}
declare module 'refractor/lang/false.js' {
  declare module.exports: $Exports<'refractor/lang/false'>;
}
declare module 'refractor/lang/firestore-security-rules.js' {
  declare module.exports: $Exports<'refractor/lang/firestore-security-rules'>;
}
declare module 'refractor/lang/flow.js' {
  declare module.exports: $Exports<'refractor/lang/flow'>;
}
declare module 'refractor/lang/fortran.js' {
  declare module.exports: $Exports<'refractor/lang/fortran'>;
}
declare module 'refractor/lang/fsharp.js' {
  declare module.exports: $Exports<'refractor/lang/fsharp'>;
}
declare module 'refractor/lang/ftl.js' {
  declare module.exports: $Exports<'refractor/lang/ftl'>;
}
declare module 'refractor/lang/gcode.js' {
  declare module.exports: $Exports<'refractor/lang/gcode'>;
}
declare module 'refractor/lang/gdscript.js' {
  declare module.exports: $Exports<'refractor/lang/gdscript'>;
}
declare module 'refractor/lang/gedcom.js' {
  declare module.exports: $Exports<'refractor/lang/gedcom'>;
}
declare module 'refractor/lang/gherkin.js' {
  declare module.exports: $Exports<'refractor/lang/gherkin'>;
}
declare module 'refractor/lang/git.js' {
  declare module.exports: $Exports<'refractor/lang/git'>;
}
declare module 'refractor/lang/glsl.js' {
  declare module.exports: $Exports<'refractor/lang/glsl'>;
}
declare module 'refractor/lang/gml.js' {
  declare module.exports: $Exports<'refractor/lang/gml'>;
}
declare module 'refractor/lang/go.js' {
  declare module.exports: $Exports<'refractor/lang/go'>;
}
declare module 'refractor/lang/graphql.js' {
  declare module.exports: $Exports<'refractor/lang/graphql'>;
}
declare module 'refractor/lang/groovy.js' {
  declare module.exports: $Exports<'refractor/lang/groovy'>;
}
declare module 'refractor/lang/haml.js' {
  declare module.exports: $Exports<'refractor/lang/haml'>;
}
declare module 'refractor/lang/handlebars.js' {
  declare module.exports: $Exports<'refractor/lang/handlebars'>;
}
declare module 'refractor/lang/haskell.js' {
  declare module.exports: $Exports<'refractor/lang/haskell'>;
}
declare module 'refractor/lang/haxe.js' {
  declare module.exports: $Exports<'refractor/lang/haxe'>;
}
declare module 'refractor/lang/hcl.js' {
  declare module.exports: $Exports<'refractor/lang/hcl'>;
}
declare module 'refractor/lang/hlsl.js' {
  declare module.exports: $Exports<'refractor/lang/hlsl'>;
}
declare module 'refractor/lang/hpkp.js' {
  declare module.exports: $Exports<'refractor/lang/hpkp'>;
}
declare module 'refractor/lang/hsts.js' {
  declare module.exports: $Exports<'refractor/lang/hsts'>;
}
declare module 'refractor/lang/http.js' {
  declare module.exports: $Exports<'refractor/lang/http'>;
}
declare module 'refractor/lang/ichigojam.js' {
  declare module.exports: $Exports<'refractor/lang/ichigojam'>;
}
declare module 'refractor/lang/icon.js' {
  declare module.exports: $Exports<'refractor/lang/icon'>;
}
declare module 'refractor/lang/icu-message-format.js' {
  declare module.exports: $Exports<'refractor/lang/icu-message-format'>;
}
declare module 'refractor/lang/idris.js' {
  declare module.exports: $Exports<'refractor/lang/idris'>;
}
declare module 'refractor/lang/iecst.js' {
  declare module.exports: $Exports<'refractor/lang/iecst'>;
}
declare module 'refractor/lang/ignore.js' {
  declare module.exports: $Exports<'refractor/lang/ignore'>;
}
declare module 'refractor/lang/inform7.js' {
  declare module.exports: $Exports<'refractor/lang/inform7'>;
}
declare module 'refractor/lang/ini.js' {
  declare module.exports: $Exports<'refractor/lang/ini'>;
}
declare module 'refractor/lang/io.js' {
  declare module.exports: $Exports<'refractor/lang/io'>;
}
declare module 'refractor/lang/j.js' {
  declare module.exports: $Exports<'refractor/lang/j'>;
}
declare module 'refractor/lang/java.js' {
  declare module.exports: $Exports<'refractor/lang/java'>;
}
declare module 'refractor/lang/javadoc.js' {
  declare module.exports: $Exports<'refractor/lang/javadoc'>;
}
declare module 'refractor/lang/javadoclike.js' {
  declare module.exports: $Exports<'refractor/lang/javadoclike'>;
}
declare module 'refractor/lang/javascript.js' {
  declare module.exports: $Exports<'refractor/lang/javascript'>;
}
declare module 'refractor/lang/javastacktrace.js' {
  declare module.exports: $Exports<'refractor/lang/javastacktrace'>;
}
declare module 'refractor/lang/jexl.js' {
  declare module.exports: $Exports<'refractor/lang/jexl'>;
}
declare module 'refractor/lang/jolie.js' {
  declare module.exports: $Exports<'refractor/lang/jolie'>;
}
declare module 'refractor/lang/jq.js' {
  declare module.exports: $Exports<'refractor/lang/jq'>;
}
declare module 'refractor/lang/js-extras.js' {
  declare module.exports: $Exports<'refractor/lang/js-extras'>;
}
declare module 'refractor/lang/js-templates.js' {
  declare module.exports: $Exports<'refractor/lang/js-templates'>;
}
declare module 'refractor/lang/jsdoc.js' {
  declare module.exports: $Exports<'refractor/lang/jsdoc'>;
}
declare module 'refractor/lang/json.js' {
  declare module.exports: $Exports<'refractor/lang/json'>;
}
declare module 'refractor/lang/json5.js' {
  declare module.exports: $Exports<'refractor/lang/json5'>;
}
declare module 'refractor/lang/jsonp.js' {
  declare module.exports: $Exports<'refractor/lang/jsonp'>;
}
declare module 'refractor/lang/jsstacktrace.js' {
  declare module.exports: $Exports<'refractor/lang/jsstacktrace'>;
}
declare module 'refractor/lang/jsx.js' {
  declare module.exports: $Exports<'refractor/lang/jsx'>;
}
declare module 'refractor/lang/julia.js' {
  declare module.exports: $Exports<'refractor/lang/julia'>;
}
declare module 'refractor/lang/keyman.js' {
  declare module.exports: $Exports<'refractor/lang/keyman'>;
}
declare module 'refractor/lang/kotlin.js' {
  declare module.exports: $Exports<'refractor/lang/kotlin'>;
}
declare module 'refractor/lang/kumir.js' {
  declare module.exports: $Exports<'refractor/lang/kumir'>;
}
declare module 'refractor/lang/latex.js' {
  declare module.exports: $Exports<'refractor/lang/latex'>;
}
declare module 'refractor/lang/latte.js' {
  declare module.exports: $Exports<'refractor/lang/latte'>;
}
declare module 'refractor/lang/less.js' {
  declare module.exports: $Exports<'refractor/lang/less'>;
}
declare module 'refractor/lang/lilypond.js' {
  declare module.exports: $Exports<'refractor/lang/lilypond'>;
}
declare module 'refractor/lang/liquid.js' {
  declare module.exports: $Exports<'refractor/lang/liquid'>;
}
declare module 'refractor/lang/lisp.js' {
  declare module.exports: $Exports<'refractor/lang/lisp'>;
}
declare module 'refractor/lang/livescript.js' {
  declare module.exports: $Exports<'refractor/lang/livescript'>;
}
declare module 'refractor/lang/llvm.js' {
  declare module.exports: $Exports<'refractor/lang/llvm'>;
}
declare module 'refractor/lang/log.js' {
  declare module.exports: $Exports<'refractor/lang/log'>;
}
declare module 'refractor/lang/lolcode.js' {
  declare module.exports: $Exports<'refractor/lang/lolcode'>;
}
declare module 'refractor/lang/lua.js' {
  declare module.exports: $Exports<'refractor/lang/lua'>;
}
declare module 'refractor/lang/makefile.js' {
  declare module.exports: $Exports<'refractor/lang/makefile'>;
}
declare module 'refractor/lang/markdown.js' {
  declare module.exports: $Exports<'refractor/lang/markdown'>;
}
declare module 'refractor/lang/markup-templating.js' {
  declare module.exports: $Exports<'refractor/lang/markup-templating'>;
}
declare module 'refractor/lang/markup.js' {
  declare module.exports: $Exports<'refractor/lang/markup'>;
}
declare module 'refractor/lang/matlab.js' {
  declare module.exports: $Exports<'refractor/lang/matlab'>;
}
declare module 'refractor/lang/mel.js' {
  declare module.exports: $Exports<'refractor/lang/mel'>;
}
declare module 'refractor/lang/mizar.js' {
  declare module.exports: $Exports<'refractor/lang/mizar'>;
}
declare module 'refractor/lang/mongodb.js' {
  declare module.exports: $Exports<'refractor/lang/mongodb'>;
}
declare module 'refractor/lang/monkey.js' {
  declare module.exports: $Exports<'refractor/lang/monkey'>;
}
declare module 'refractor/lang/moonscript.js' {
  declare module.exports: $Exports<'refractor/lang/moonscript'>;
}
declare module 'refractor/lang/n1ql.js' {
  declare module.exports: $Exports<'refractor/lang/n1ql'>;
}
declare module 'refractor/lang/n4js.js' {
  declare module.exports: $Exports<'refractor/lang/n4js'>;
}
declare module 'refractor/lang/nand2tetris-hdl.js' {
  declare module.exports: $Exports<'refractor/lang/nand2tetris-hdl'>;
}
declare module 'refractor/lang/naniscript.js' {
  declare module.exports: $Exports<'refractor/lang/naniscript'>;
}
declare module 'refractor/lang/nasm.js' {
  declare module.exports: $Exports<'refractor/lang/nasm'>;
}
declare module 'refractor/lang/neon.js' {
  declare module.exports: $Exports<'refractor/lang/neon'>;
}
declare module 'refractor/lang/nevod.js' {
  declare module.exports: $Exports<'refractor/lang/nevod'>;
}
declare module 'refractor/lang/nginx.js' {
  declare module.exports: $Exports<'refractor/lang/nginx'>;
}
declare module 'refractor/lang/nim.js' {
  declare module.exports: $Exports<'refractor/lang/nim'>;
}
declare module 'refractor/lang/nix.js' {
  declare module.exports: $Exports<'refractor/lang/nix'>;
}
declare module 'refractor/lang/nsis.js' {
  declare module.exports: $Exports<'refractor/lang/nsis'>;
}
declare module 'refractor/lang/objectivec.js' {
  declare module.exports: $Exports<'refractor/lang/objectivec'>;
}
declare module 'refractor/lang/ocaml.js' {
  declare module.exports: $Exports<'refractor/lang/ocaml'>;
}
declare module 'refractor/lang/opencl.js' {
  declare module.exports: $Exports<'refractor/lang/opencl'>;
}
declare module 'refractor/lang/openqasm.js' {
  declare module.exports: $Exports<'refractor/lang/openqasm'>;
}
declare module 'refractor/lang/oz.js' {
  declare module.exports: $Exports<'refractor/lang/oz'>;
}
declare module 'refractor/lang/parigp.js' {
  declare module.exports: $Exports<'refractor/lang/parigp'>;
}
declare module 'refractor/lang/parser.js' {
  declare module.exports: $Exports<'refractor/lang/parser'>;
}
declare module 'refractor/lang/pascal.js' {
  declare module.exports: $Exports<'refractor/lang/pascal'>;
}
declare module 'refractor/lang/pascaligo.js' {
  declare module.exports: $Exports<'refractor/lang/pascaligo'>;
}
declare module 'refractor/lang/pcaxis.js' {
  declare module.exports: $Exports<'refractor/lang/pcaxis'>;
}
declare module 'refractor/lang/peoplecode.js' {
  declare module.exports: $Exports<'refractor/lang/peoplecode'>;
}
declare module 'refractor/lang/perl.js' {
  declare module.exports: $Exports<'refractor/lang/perl'>;
}
declare module 'refractor/lang/php-extras.js' {
  declare module.exports: $Exports<'refractor/lang/php-extras'>;
}
declare module 'refractor/lang/php.js' {
  declare module.exports: $Exports<'refractor/lang/php'>;
}
declare module 'refractor/lang/phpdoc.js' {
  declare module.exports: $Exports<'refractor/lang/phpdoc'>;
}
declare module 'refractor/lang/plsql.js' {
  declare module.exports: $Exports<'refractor/lang/plsql'>;
}
declare module 'refractor/lang/powerquery.js' {
  declare module.exports: $Exports<'refractor/lang/powerquery'>;
}
declare module 'refractor/lang/powershell.js' {
  declare module.exports: $Exports<'refractor/lang/powershell'>;
}
declare module 'refractor/lang/processing.js' {
  declare module.exports: $Exports<'refractor/lang/processing'>;
}
declare module 'refractor/lang/prolog.js' {
  declare module.exports: $Exports<'refractor/lang/prolog'>;
}
declare module 'refractor/lang/promql.js' {
  declare module.exports: $Exports<'refractor/lang/promql'>;
}
declare module 'refractor/lang/properties.js' {
  declare module.exports: $Exports<'refractor/lang/properties'>;
}
declare module 'refractor/lang/protobuf.js' {
  declare module.exports: $Exports<'refractor/lang/protobuf'>;
}
declare module 'refractor/lang/psl.js' {
  declare module.exports: $Exports<'refractor/lang/psl'>;
}
declare module 'refractor/lang/pug.js' {
  declare module.exports: $Exports<'refractor/lang/pug'>;
}
declare module 'refractor/lang/puppet.js' {
  declare module.exports: $Exports<'refractor/lang/puppet'>;
}
declare module 'refractor/lang/pure.js' {
  declare module.exports: $Exports<'refractor/lang/pure'>;
}
declare module 'refractor/lang/purebasic.js' {
  declare module.exports: $Exports<'refractor/lang/purebasic'>;
}
declare module 'refractor/lang/purescript.js' {
  declare module.exports: $Exports<'refractor/lang/purescript'>;
}
declare module 'refractor/lang/python.js' {
  declare module.exports: $Exports<'refractor/lang/python'>;
}
declare module 'refractor/lang/q.js' {
  declare module.exports: $Exports<'refractor/lang/q'>;
}
declare module 'refractor/lang/qml.js' {
  declare module.exports: $Exports<'refractor/lang/qml'>;
}
declare module 'refractor/lang/qore.js' {
  declare module.exports: $Exports<'refractor/lang/qore'>;
}
declare module 'refractor/lang/qsharp.js' {
  declare module.exports: $Exports<'refractor/lang/qsharp'>;
}
declare module 'refractor/lang/r.js' {
  declare module.exports: $Exports<'refractor/lang/r'>;
}
declare module 'refractor/lang/racket.js' {
  declare module.exports: $Exports<'refractor/lang/racket'>;
}
declare module 'refractor/lang/reason.js' {
  declare module.exports: $Exports<'refractor/lang/reason'>;
}
declare module 'refractor/lang/regex.js' {
  declare module.exports: $Exports<'refractor/lang/regex'>;
}
declare module 'refractor/lang/rego.js' {
  declare module.exports: $Exports<'refractor/lang/rego'>;
}
declare module 'refractor/lang/renpy.js' {
  declare module.exports: $Exports<'refractor/lang/renpy'>;
}
declare module 'refractor/lang/rest.js' {
  declare module.exports: $Exports<'refractor/lang/rest'>;
}
declare module 'refractor/lang/rip.js' {
  declare module.exports: $Exports<'refractor/lang/rip'>;
}
declare module 'refractor/lang/roboconf.js' {
  declare module.exports: $Exports<'refractor/lang/roboconf'>;
}
declare module 'refractor/lang/robotframework.js' {
  declare module.exports: $Exports<'refractor/lang/robotframework'>;
}
declare module 'refractor/lang/ruby.js' {
  declare module.exports: $Exports<'refractor/lang/ruby'>;
}
declare module 'refractor/lang/rust.js' {
  declare module.exports: $Exports<'refractor/lang/rust'>;
}
declare module 'refractor/lang/sas.js' {
  declare module.exports: $Exports<'refractor/lang/sas'>;
}
declare module 'refractor/lang/sass.js' {
  declare module.exports: $Exports<'refractor/lang/sass'>;
}
declare module 'refractor/lang/scala.js' {
  declare module.exports: $Exports<'refractor/lang/scala'>;
}
declare module 'refractor/lang/scheme.js' {
  declare module.exports: $Exports<'refractor/lang/scheme'>;
}
declare module 'refractor/lang/scss.js' {
  declare module.exports: $Exports<'refractor/lang/scss'>;
}
declare module 'refractor/lang/shell-session.js' {
  declare module.exports: $Exports<'refractor/lang/shell-session'>;
}
declare module 'refractor/lang/smali.js' {
  declare module.exports: $Exports<'refractor/lang/smali'>;
}
declare module 'refractor/lang/smalltalk.js' {
  declare module.exports: $Exports<'refractor/lang/smalltalk'>;
}
declare module 'refractor/lang/smarty.js' {
  declare module.exports: $Exports<'refractor/lang/smarty'>;
}
declare module 'refractor/lang/sml.js' {
  declare module.exports: $Exports<'refractor/lang/sml'>;
}
declare module 'refractor/lang/solidity.js' {
  declare module.exports: $Exports<'refractor/lang/solidity'>;
}
declare module 'refractor/lang/solution-file.js' {
  declare module.exports: $Exports<'refractor/lang/solution-file'>;
}
declare module 'refractor/lang/soy.js' {
  declare module.exports: $Exports<'refractor/lang/soy'>;
}
declare module 'refractor/lang/sparql.js' {
  declare module.exports: $Exports<'refractor/lang/sparql'>;
}
declare module 'refractor/lang/splunk-spl.js' {
  declare module.exports: $Exports<'refractor/lang/splunk-spl'>;
}
declare module 'refractor/lang/sqf.js' {
  declare module.exports: $Exports<'refractor/lang/sqf'>;
}
declare module 'refractor/lang/sql.js' {
  declare module.exports: $Exports<'refractor/lang/sql'>;
}
declare module 'refractor/lang/squirrel.js' {
  declare module.exports: $Exports<'refractor/lang/squirrel'>;
}
declare module 'refractor/lang/stan.js' {
  declare module.exports: $Exports<'refractor/lang/stan'>;
}
declare module 'refractor/lang/stylus.js' {
  declare module.exports: $Exports<'refractor/lang/stylus'>;
}
declare module 'refractor/lang/swift.js' {
  declare module.exports: $Exports<'refractor/lang/swift'>;
}
declare module 'refractor/lang/t4-cs.js' {
  declare module.exports: $Exports<'refractor/lang/t4-cs'>;
}
declare module 'refractor/lang/t4-templating.js' {
  declare module.exports: $Exports<'refractor/lang/t4-templating'>;
}
declare module 'refractor/lang/t4-vb.js' {
  declare module.exports: $Exports<'refractor/lang/t4-vb'>;
}
declare module 'refractor/lang/tap.js' {
  declare module.exports: $Exports<'refractor/lang/tap'>;
}
declare module 'refractor/lang/tcl.js' {
  declare module.exports: $Exports<'refractor/lang/tcl'>;
}
declare module 'refractor/lang/textile.js' {
  declare module.exports: $Exports<'refractor/lang/textile'>;
}
declare module 'refractor/lang/toml.js' {
  declare module.exports: $Exports<'refractor/lang/toml'>;
}
declare module 'refractor/lang/tsx.js' {
  declare module.exports: $Exports<'refractor/lang/tsx'>;
}
declare module 'refractor/lang/tt2.js' {
  declare module.exports: $Exports<'refractor/lang/tt2'>;
}
declare module 'refractor/lang/turtle.js' {
  declare module.exports: $Exports<'refractor/lang/turtle'>;
}
declare module 'refractor/lang/twig.js' {
  declare module.exports: $Exports<'refractor/lang/twig'>;
}
declare module 'refractor/lang/typescript.js' {
  declare module.exports: $Exports<'refractor/lang/typescript'>;
}
declare module 'refractor/lang/typoscript.js' {
  declare module.exports: $Exports<'refractor/lang/typoscript'>;
}
declare module 'refractor/lang/unrealscript.js' {
  declare module.exports: $Exports<'refractor/lang/unrealscript'>;
}
declare module 'refractor/lang/uri.js' {
  declare module.exports: $Exports<'refractor/lang/uri'>;
}
declare module 'refractor/lang/v.js' {
  declare module.exports: $Exports<'refractor/lang/v'>;
}
declare module 'refractor/lang/vala.js' {
  declare module.exports: $Exports<'refractor/lang/vala'>;
}
declare module 'refractor/lang/vbnet.js' {
  declare module.exports: $Exports<'refractor/lang/vbnet'>;
}
declare module 'refractor/lang/velocity.js' {
  declare module.exports: $Exports<'refractor/lang/velocity'>;
}
declare module 'refractor/lang/verilog.js' {
  declare module.exports: $Exports<'refractor/lang/verilog'>;
}
declare module 'refractor/lang/vhdl.js' {
  declare module.exports: $Exports<'refractor/lang/vhdl'>;
}
declare module 'refractor/lang/vim.js' {
  declare module.exports: $Exports<'refractor/lang/vim'>;
}
declare module 'refractor/lang/visual-basic.js' {
  declare module.exports: $Exports<'refractor/lang/visual-basic'>;
}
declare module 'refractor/lang/warpscript.js' {
  declare module.exports: $Exports<'refractor/lang/warpscript'>;
}
declare module 'refractor/lang/wasm.js' {
  declare module.exports: $Exports<'refractor/lang/wasm'>;
}
declare module 'refractor/lang/wiki.js' {
  declare module.exports: $Exports<'refractor/lang/wiki'>;
}
declare module 'refractor/lang/wolfram.js' {
  declare module.exports: $Exports<'refractor/lang/wolfram'>;
}
declare module 'refractor/lang/xeora.js' {
  declare module.exports: $Exports<'refractor/lang/xeora'>;
}
declare module 'refractor/lang/xml-doc.js' {
  declare module.exports: $Exports<'refractor/lang/xml-doc'>;
}
declare module 'refractor/lang/xojo.js' {
  declare module.exports: $Exports<'refractor/lang/xojo'>;
}
declare module 'refractor/lang/xquery.js' {
  declare module.exports: $Exports<'refractor/lang/xquery'>;
}
declare module 'refractor/lang/yaml.js' {
  declare module.exports: $Exports<'refractor/lang/yaml'>;
}
declare module 'refractor/lang/yang.js' {
  declare module.exports: $Exports<'refractor/lang/yang'>;
}
declare module 'refractor/lang/zig.js' {
  declare module.exports: $Exports<'refractor/lang/zig'>;
}
declare module 'refractor/lib/all.js' {
  declare module.exports: $Exports<'refractor/lib/all'>;
}
declare module 'refractor/lib/common.js' {
  declare module.exports: $Exports<'refractor/lib/common'>;
}
declare module 'refractor/lib/core.js' {
  declare module.exports: $Exports<'refractor/lib/core'>;
}
