// flow-typed signature: 9dd08c763b14ad058eb2a93d1e39507a
// flow-typed version: <<STUB>>/style-loader_v^1.2.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'style-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'style-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'style-loader/dist' {
  declare module.exports: any;
}

declare module 'style-loader/dist/runtime/injectStylesIntoLinkTag' {
  declare module.exports: any;
}

declare module 'style-loader/dist/runtime/injectStylesIntoStyleTag' {
  declare module.exports: any;
}

declare module 'style-loader/dist/runtime/isEqualLocals' {
  declare module.exports: any;
}

// Filename aliases
declare module 'style-loader/dist/cjs.js' {
  declare module.exports: $Exports<'style-loader/dist/cjs'>;
}
declare module 'style-loader/dist/index' {
  declare module.exports: $Exports<'style-loader/dist'>;
}
declare module 'style-loader/dist/index.js' {
  declare module.exports: $Exports<'style-loader/dist'>;
}
declare module 'style-loader/dist/runtime/injectStylesIntoLinkTag.js' {
  declare module.exports: $Exports<'style-loader/dist/runtime/injectStylesIntoLinkTag'>;
}
declare module 'style-loader/dist/runtime/injectStylesIntoStyleTag.js' {
  declare module.exports: $Exports<'style-loader/dist/runtime/injectStylesIntoStyleTag'>;
}
declare module 'style-loader/dist/runtime/isEqualLocals.js' {
  declare module.exports: $Exports<'style-loader/dist/runtime/isEqualLocals'>;
}
