// flow-typed signature: d19c29bd341a8983ceb337a7790edf91
// flow-typed version: <<STUB>>/stylelint-config-idiomatic-order_v^8.1.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-idiomatic-order'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-idiomatic-order' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-config-idiomatic-order/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-config-idiomatic-order/index' {
  declare module.exports: $Exports<'stylelint-config-idiomatic-order'>;
}
declare module 'stylelint-config-idiomatic-order/index.js' {
  declare module.exports: $Exports<'stylelint-config-idiomatic-order'>;
}
declare module 'stylelint-config-idiomatic-order/test/test.js' {
  declare module.exports: $Exports<'stylelint-config-idiomatic-order/test/test'>;
}
