// flow-typed signature: 21b003b3abb138bbb2f58dc76aab0a37
// flow-typed version: <<STUB>>/weaktuplemap_v^1.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'weaktuplemap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'weaktuplemap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'weaktuplemap/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'weaktuplemap/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'weaktuplemap/__tests__/index.test.js' {
  declare module.exports: $Exports<'weaktuplemap/__tests__/index.test'>;
}
declare module 'weaktuplemap/dist/index.js' {
  declare module.exports: $Exports<'weaktuplemap/dist/index'>;
}
declare module 'weaktuplemap/index' {
  declare module.exports: $Exports<'weaktuplemap'>;
}
declare module 'weaktuplemap/index.js' {
  declare module.exports: $Exports<'weaktuplemap'>;
}
