// flow-typed signature: a86302ec56f544f5f77a72b340c3a982
// flow-typed version: <<STUB>>/workbox-webpack-plugin_v6.5.3/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'workbox-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'workbox-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'workbox-webpack-plugin/build/generate-sw' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/inject-manifest' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/get-asset-hash' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/get-manifest-entries-from-compilation' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/get-script-files-for-chunks' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/get-sourcemap-asset-name' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/relative-to-output-path' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/resolve-webpack-url' {
  declare module.exports: any;
}

// Filename aliases
declare module 'workbox-webpack-plugin/build/generate-sw.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/generate-sw'>;
}
declare module 'workbox-webpack-plugin/build/index' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build'>;
}
declare module 'workbox-webpack-plugin/build/index.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build'>;
}
declare module 'workbox-webpack-plugin/build/inject-manifest.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/inject-manifest'>;
}
declare module 'workbox-webpack-plugin/build/lib/get-asset-hash.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/get-asset-hash'>;
}
declare module 'workbox-webpack-plugin/build/lib/get-manifest-entries-from-compilation.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/get-manifest-entries-from-compilation'>;
}
declare module 'workbox-webpack-plugin/build/lib/get-script-files-for-chunks.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/get-script-files-for-chunks'>;
}
declare module 'workbox-webpack-plugin/build/lib/get-sourcemap-asset-name.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/get-sourcemap-asset-name'>;
}
declare module 'workbox-webpack-plugin/build/lib/relative-to-output-path.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/relative-to-output-path'>;
}
declare module 'workbox-webpack-plugin/build/lib/resolve-webpack-url.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/resolve-webpack-url'>;
}
