// flow-typed signature: f84c93c5335ad9c36684cc95ca54b099
// flow-typed version: <<STUB>>/@mstange/offline-plugin_v^5.0.6/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mstange/offline-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mstange/offline-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mstange/offline-plugin/lib/app-cache' {
  declare module.exports: any;
}

declare module '@mstange/offline-plugin/lib/default-options' {
  declare module.exports: any;
}

declare module '@mstange/offline-plugin/lib/index' {
  declare module.exports: any;
}

declare module '@mstange/offline-plugin/lib/loaders/fonts-css' {
  declare module.exports: any;
}

declare module '@mstange/offline-plugin/lib/loaders/index' {
  declare module.exports: any;
}

declare module '@mstange/offline-plugin/lib/misc/async-waituntil' {
  declare module.exports: any;
}

declare module '@mstange/offline-plugin/lib/misc/get-uglify-plugin' {
  declare module.exports: any;
}

declare module '@mstange/offline-plugin/lib/misc/runtime-loader' {
  declare module.exports: any;
}

declare module '@mstange/offline-plugin/lib/misc/sw-loader' {
  declare module.exports: any;
}

declare module '@mstange/offline-plugin/lib/misc/sw-polyfill' {
  declare module.exports: any;
}

declare module '@mstange/offline-plugin/lib/misc/sw-template' {
  declare module.exports: any;
}

declare module '@mstange/offline-plugin/lib/misc/utils' {
  declare module.exports: any;
}

declare module '@mstange/offline-plugin/lib/service-worker' {
  declare module.exports: any;
}

declare module '@mstange/offline-plugin/runtime' {
  declare module.exports: any;
}

declare module '@mstange/offline-plugin/tpls/empty-entry' {
  declare module.exports: any;
}

declare module '@mstange/offline-plugin/tpls/runtime-template' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mstange/offline-plugin/lib/app-cache.js' {
  declare module.exports: $Exports<'@mstange/offline-plugin/lib/app-cache'>;
}
declare module '@mstange/offline-plugin/lib/default-options.js' {
  declare module.exports: $Exports<'@mstange/offline-plugin/lib/default-options'>;
}
declare module '@mstange/offline-plugin/lib/index.js' {
  declare module.exports: $Exports<'@mstange/offline-plugin/lib/index'>;
}
declare module '@mstange/offline-plugin/lib/loaders/fonts-css.js' {
  declare module.exports: $Exports<'@mstange/offline-plugin/lib/loaders/fonts-css'>;
}
declare module '@mstange/offline-plugin/lib/loaders/index.js' {
  declare module.exports: $Exports<'@mstange/offline-plugin/lib/loaders/index'>;
}
declare module '@mstange/offline-plugin/lib/misc/async-waituntil.js' {
  declare module.exports: $Exports<'@mstange/offline-plugin/lib/misc/async-waituntil'>;
}
declare module '@mstange/offline-plugin/lib/misc/get-uglify-plugin.js' {
  declare module.exports: $Exports<'@mstange/offline-plugin/lib/misc/get-uglify-plugin'>;
}
declare module '@mstange/offline-plugin/lib/misc/runtime-loader.js' {
  declare module.exports: $Exports<'@mstange/offline-plugin/lib/misc/runtime-loader'>;
}
declare module '@mstange/offline-plugin/lib/misc/sw-loader.js' {
  declare module.exports: $Exports<'@mstange/offline-plugin/lib/misc/sw-loader'>;
}
declare module '@mstange/offline-plugin/lib/misc/sw-polyfill.js' {
  declare module.exports: $Exports<'@mstange/offline-plugin/lib/misc/sw-polyfill'>;
}
declare module '@mstange/offline-plugin/lib/misc/sw-template.js' {
  declare module.exports: $Exports<'@mstange/offline-plugin/lib/misc/sw-template'>;
}
declare module '@mstange/offline-plugin/lib/misc/utils.js' {
  declare module.exports: $Exports<'@mstange/offline-plugin/lib/misc/utils'>;
}
declare module '@mstange/offline-plugin/lib/service-worker.js' {
  declare module.exports: $Exports<'@mstange/offline-plugin/lib/service-worker'>;
}
declare module '@mstange/offline-plugin/runtime.js' {
  declare module.exports: $Exports<'@mstange/offline-plugin/runtime'>;
}
declare module '@mstange/offline-plugin/tpls/empty-entry.js' {
  declare module.exports: $Exports<'@mstange/offline-plugin/tpls/empty-entry'>;
}
declare module '@mstange/offline-plugin/tpls/runtime-template.js' {
  declare module.exports: $Exports<'@mstange/offline-plugin/tpls/runtime-template'>;
}
